### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jegyvasarlas** [Zero6992/chatGPT-discord-bot#112]
Traceback (most recent call last):
  File "/home/user/Desktop/bot/main.py", line 1, in <module>
    from src import bot
  File "/home/user/Desktop/bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/home/user/Desktop/bot/src/responses.py", line 18, in <module>
    config = get_config()
  File "/home/user/Desktop/bot/src/responses.py", line 14, in get_config
    config = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 45 (char 146)

**Comment by aW3ikun** [comment]
Could you check your formatting of `config.json`?

**Comment by Zero6992** [comment]
formatting problem
