### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Francy02** [Zero6992/chatGPT-discord-bot#114]
I uploaded your project to Replit to host the bot with uptimerobot.
When I run the bot I get this error, API Key in correct:

ERROR    src.bot -> Error while sending starting prompt: Incorrect API key provided: sk-MiDon***************************************mf5s. You can find your API key at https://beta.openai.com.
Traceback (most recent call last):
  File "/home/runner/chatGPT-discord-bot/src/bot.py", line 80, in send_start_prompt
    responseMessage = await responses.handle_response(prompt)
  File "/home/runner/chatGPT-discord-bot/src/responses.py", line 23, in handle_response
    response = await sync_to_async(openai.Completion.create)(
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 599, in _interpret_response
    self._interpret_response_line(
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 655, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: sk-MiDon***************************************mf5s. You can find your API key at https://beta.openai.com.

**Comment by aW3ikun** [comment]
`Incorrect API key provided`. 
Following README.md entirely.
