### ISSUE TITLE
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by 0x3639** [Zero6992/chatGPT-discord-bot#117]
Just launched the bot with docker-compose.  The bot seems to be working, however I'm getting this error message in the logs.  

```
2023-01-13 16:03:54 INFO     src.bot -> Send starting prompt with size 11
2023-01-13 16:03:56 ERROR    src.bot -> Error while sending starting prompt: 403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "/DiscordBot/src/bot.py", line 83, in send_start_prompt
    await channel.send(responseMessage)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```
I'm assuming it has something to do with the Channel ID (which is correct).  However I'm not sure.  Any thoughts on how to fix this?

**Comment by refi-git** [comment]
your bot has no access to write to that channel, give it access in discord

**Comment by 0x3639** [comment]
Thank you for that feedback.  I will correct that.

**Comment by 0x3639** [comment]
We gave the bot the necessary permissions, restarted the bot, and still get the missing access error.  Thank you for your support.  

![image (4)](https://user-images.githubusercontent.com/5406130/212537304-b7a4d7ee-25cf-410c-aced-9d978ab13a3f.png)


```
2023-01-15 11:10:01 INFO     src.bot -> Send starting prompt with size 11
2023-01-15 11:10:03 ERROR    src.bot -> Error while sending starting prompt: 403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "/DiscordBot/src/bot.py", line 83, in send_start_prompt
    await channel.send(responseMessage)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by 0x3639** [comment]
Looks like the bot had permissions to write, but their role was not applied to the channel.  So I applied the chatGPT role (with the ability to write messages) to the channel and the error message disappeared.
