### ISSUE TITLE
But stuck in "is thinking..." for a while and ConnectionError in the logs.

### ISSUE THREAD

**Issue by refi-git** [Zero6992/chatGPT-discord-bot#119]
Running this bot in docker and sometimes it stuck with "is thinking..." for a while.
In the logs I found that there was some connection error but the issue was not on my side for sure.
Do you experience such connection errors with the OpenAI API sometimes?

2023-01-14T14:15:32.472493465Z Traceback (most recent call last):
2023-01-14T14:15:32.472512409Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-01-14T14:15:32.472529908Z     httplib_response = self._make_request(
2023-01-14T14:15:32.472546241Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
2023-01-14T14:15:32.472562778Z     six.raise_from(e, None)
2023-01-14T14:15:32.472578444Z   File "<string>", line 3, in raise_from
2023-01-14T14:15:32.472594740Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
2023-01-14T14:15:32.472611110Z     httplib_response = conn.getresponse()
2023-01-14T14:15:32.472626851Z   File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
2023-01-14T14:15:32.472643091Z     response.begin()
2023-01-14T14:15:32.472658720Z   File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
2023-01-14T14:15:32.472674831Z     version, status, reason = self._read_status()
2023-01-14T14:15:32.472690590Z   File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
2023-01-14T14:15:32.472706738Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2023-01-14T14:15:32.472722849Z   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
2023-01-14T14:15:32.472738941Z     return self._sock.recv_into(b)
2023-01-14T14:15:32.472754552Z   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
2023-01-14T14:15:32.472770551Z     return self.read(nbytes, buffer)
2023-01-14T14:15:32.472786199Z   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
2023-01-14T14:15:32.472832754Z     return self._sslobj.read(len, buffer)
2023-01-14T14:15:32.472848698Z ConnectionResetError: [Errno 104] Connection reset by peer
2023-01-14T14:15:32.472863475Z
2023-01-14T14:15:32.472877530Z During handling of the above exception, another exception occurred:
2023-01-14T14:15:32.472892197Z
2023-01-14T14:15:32.472906308Z Traceback (most recent call last):
2023-01-14T14:15:32.472920678Z   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
2023-01-14T14:15:32.472935677Z     resp = conn.urlopen(
2023-01-14T14:15:32.472950121Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-01-14T14:15:32.472965269Z     retries = retries.increment(
2023-01-14T14:15:32.472980084Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
2023-01-14T14:15:32.472995213Z     raise six.reraise(type(error), error, _stacktrace)
2023-01-14T14:15:32.473009805Z   File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
2023-01-14T14:15:32.473024879Z     raise value.with_traceback(tb)
2023-01-14T14:15:32.473042342Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-01-14T14:15:32.473058212Z     httplib_response = self._make_request(
2023-01-14T14:15:32.473072656Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
2023-01-14T14:15:32.473087804Z     six.raise_from(e, None)
2023-01-14T14:15:32.473102229Z   File "<string>", line 3, in raise_from
2023-01-14T14:15:32.473117266Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
2023-01-14T14:15:32.473132266Z     httplib_response = conn.getresponse()
2023-01-14T14:15:32.473146728Z   File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
2023-01-14T14:15:32.473161672Z     response.begin()
2023-01-14T14:15:32.473175894Z   File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
2023-01-14T14:15:32.473190783Z     version, status, reason = self._read_status()
2023-01-14T14:15:32.473205301Z   File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
2023-01-14T14:15:32.473220301Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2023-01-14T14:15:32.473235171Z   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
2023-01-14T14:15:32.473249948Z     return self._sock.recv_into(b)
2023-01-14T14:15:32.473264355Z   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
2023-01-14T14:15:32.473279262Z     return self.read(nbytes, buffer)
2023-01-14T14:15:32.473293781Z   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
2023-01-14T14:15:32.473323058Z     return self._sslobj.read(len, buffer)
2023-01-14T14:15:32.473338891Z urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-01-14T14:15:32.473354168Z
2023-01-14T14:15:32.473368298Z During handling of the above exception, another exception occurred:
2023-01-14T14:15:32.473383075Z
2023-01-14T14:15:32.473397186Z Traceback (most recent call last):
2023-01-14T14:15:32.473411537Z   File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 356, in request_raw
2023-01-14T14:15:32.473426537Z     result = _thread_context.session.request(
2023-01-14T14:15:32.473441277Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
2023-01-14T14:15:32.473456277Z     resp = self.send(prep, **send_kwargs)
2023-01-14T14:15:32.473470740Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
2023-01-14T14:15:32.473485721Z     r = adapter.send(request, **kwargs)
2023-01-14T14:15:32.473500147Z   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
2023-01-14T14:15:32.473515054Z     raise ConnectionError(err, request=request)
2023-01-14T14:15:32.473529701Z requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-01-14T14:15:32.473544775Z
2023-01-14T14:15:32.473558886Z The above exception was the direct cause of the following exception:
2023-01-14T14:15:32.473573589Z
2023-01-14T14:15:32.473587663Z Traceback (most recent call last):
2023-01-14T14:15:32.473603274Z   File "/DiscordBot/src/bot.py", line 25, in send_message
2023-01-14T14:15:32.473618718Z     response = f"{response}{await responses.handle_response(user_message)}"
2023-01-14T14:15:32.473633662Z   File "/DiscordBot/src/responses.py", line 22, in handle_response
2023-01-14T14:15:32.473648495Z     response = await sync_to_async(openai.Completion.create)(
2023-01-14T14:15:32.473663106Z   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 448, in __call__
2023-01-14T14:15:32.473678050Z     ret = await asyncio.wait_for(future, timeout=None)
2023-01-14T14:15:32.473692753Z   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
2023-01-14T14:15:32.473707587Z     return await fut
2023-01-14T14:15:32.473721882Z   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2023-01-14T14:15:32.473736845Z     result = self.fn(*self.args, **self.kwargs)
2023-01-14T14:15:32.473751308Z   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 490, in thread_handler
2023-01-14T14:15:32.473766363Z     return func(*args, **kwargs)
2023-01-14T14:15:32.473780789Z   File "/usr/local/lib/python3.8/site-packages/openai/api_resources/completion.py", line 25, in create
2023-01-14T14:15:32.473810603Z     return super().create(*args, **kwargs)
2023-01-14T14:15:32.473826288Z   File "/usr/local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 115, in create
2023-01-14T14:15:32.473841491Z     response, _, api_key = requestor.request(
2023-01-14T14:15:32.473856194Z   File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 171, in request
2023-01-14T14:15:32.473871250Z     result = self.request_raw(
2023-01-14T14:15:32.473885564Z   File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 368, in request_raw
2023-01-14T14:15:32.473900656Z     raise error.APIConnectionError("Error communicating with OpenAI") from e
2023-01-14T14:15:32.473915526Z openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by Zero6992** [comment]
It seems to be an issue with OpenAI API server,
