### ISSUE TITLE
"pip install -r requirements.txt" error

### ISSUE THREAD

**Issue by pigman8787** [Zero6992/chatGPT-discord-bot#120]
When i run "pip install -r requirements.txt"  ,I get this error below

```
"Collecting discord.py==2.1.0
  Using cached discord.py-2.1.0-py3-none-any.whl (1.1 MB)
Collecting openai==0.26.1
  Using cached openai-0.26.1.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\pigman8787\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\pigman8787\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\pigman8787\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-jn11q_nq\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-jn11q_nq\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-jn11q_nq\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-jn11q_nq\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1030: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip."
```

How can i solve this problem ?

**Comment by najx** [comment]
It's also possible that the package is not compatible with your version of Python. It seems you're using Python 3.9, you should ensure to test with an earlier version of Python such as Python 3.8 or 3.7 and see if that resolves the issue.

You can also try to install the package using the command `pip install --no-binary :all: <package>`

**Comment by pigman8787** [comment]
> 該套件可能與您的 Python 版本不相容。看起來你使用的是Python 3.9，你應該使用早期版本的Python（如Python 3.8或3.7）進行測試，看看是否能解決問題。
> 
> 您也可以嘗試使用以下命令安裝套件`pip install --no-binary :all: <package>`

I uninstall python 3.9 and install python 3.8 ,but it didn't solve this problem .

`PS C:\Users\pigman8787\Desktop\chatGPT-discord-bot-main> pip install -r requirements.txt
Collecting discord.py==2.1.0
  Using cached discord.py-2.1.0-py3-none-any.whl (1.1 MB)
Collecting openai==0.26.1
  Using cached openai-0.26.1.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\pigman8787\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\PIGMAN~1\AppData\Local\Temp\tmpe26zqqg3'
       cwd: C:\Users\pigman8787\AppData\Local\Temp\pip-install-vgowh34w\openai_66bf890deb7943caa817fa162cf3b07b
  Complete output (17 lines):
  Traceback (most recent call last):
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-5g3wqr_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-5g3wqr_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-5g3wqr_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\pigman8787\AppData\Local\Temp\pip-build-env-5g3wqr_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 13, in <module>
  UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1030: illegal multibyte sequence
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0b/de/c3d4f74cec0562d26a7393c97fb472d5555d685f2def82cb60befbd5262d/openai-0.26.1.tar.gz#sha256=85cbe75e0646ab38a0e4b4184237c69b3870721e3c1232341289966bccd98522 (from https://pypi.org/simple/openai/) (requires-python:>=3.7.1). Command errored out with exit status 1: 'C:\Users\pigman8787\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\PIGMAN~1\AppData\Local\Temp\tmpe26zqqg3' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement openai==0.26.1 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.25.0, 0.26.0, 0.26.1)
ERROR: No matching distribution found for openai==0.26.1
WARNING: You are using pip version 21.1.1; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Users\pigman8787\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.`

**Comment by aW3ikun** [comment]
There are no errors in my desktop `pip install -r requirements.txt` progress.
![image](https://user-images.githubusercontent.com/23023918/213996769-ef8cf65c-af3a-4c99-99b2-83aa0d0423d3.png)

My environment：
- Windows11
- python3.11 
- [terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701)
- [venv](https://docs.python.org/3/library/venv.html)
- PowerShell 7.3.1

**Comment by pigman8787** [comment]
Originally, my pc would not have this error in 21h2 version, but after I re-install windows 11 22h2 in my pc, this error apear,

**Comment by aW3ikun** [comment]
> Originally, my pc would not have this error in 21h2 version, but after I re-install windows 11 22h2 in my pc, this error apear.

It's not an error of the system version; I‘m also 22h2.
![image](https://user-images.githubusercontent.com/23023918/214166203-0f7142a7-772f-4ac3-9a3f-fbc01f32d805.png)

**Comment by linzack** [comment]
The cp950 issue is because Microsoft using cp950 encoding in big5 instead of utf8, every windows with zh-tw language will have this issue. if you run python under command prompt or PowerShell, and it open a file, the default decoding method will be cp950, so if the file is encoded with utf8, you will definitely get a decoding error. to solve this issue, in python code, you have to specify the encoding method when open a file in python. or just don't use command prompt / PowerShell under windows, you can install wsl2 and Linux subsystem then run python on it.

**Comment by aW3ikun** [comment]
Try to reinstall Windows in the English language. It's likely to solve this UnicodeDecodeError.
