### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by franco-rey** [Zero6992/chatGPT-discord-bot#126]
I've gotten everything to work thus far until Step 3: Run the bot on the desktop.

Originally, when trying to start the bot, I got the 

> Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

error. I since have managed to fix it, but every time I now try to run the bot, I am returned with this error:

> PS G:\Capstone\Capstone-main\UWT-ChatGPT-Discord-Bot> python3 main.py
2023-01-24 21:38:44 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Python310\lib\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "G:\Capstone\Capstone-main\UWT-ChatGPT-Discord-Bot\main.py", line 29, in <module>
    bot.run_discord_bot()
  File "G:\Capstone\Capstone-main\UWT-ChatGPT-Discord-Bot\src\bot.py", line 143, in run_discord_bot
    client.run(TOKEN)
  File "C:\Python310\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Python310\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Python310\lib\site-packages\discord\client.py", line 580, in login
    data = await self.http.static_login(token)
  File "C:\Python310\lib\site-packages\discord\http.py", line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021B1C7B6200>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Reading similar errors from other bots, people have mentioned this is the result of a wrong or invalid token. I've made new tokens and secret keys from Discord and OpenAI and have gotten the same result.

**Comment by GustavRaispits** [comment]
It is probably related to your discord bot application token, or probably you're not using the right settings, try to follow again the tutorial, the application works pretty fine on Python 3.10
