### ISSUE TITLE
problem with pip install -r requirements.txt

### ISSUE THREAD

**Issue by tonyleesos** [Zero6992/chatGPT-discord-bot#130]
PS C:\Users\user\Downloads\chatGPT-discord-bot-main\chatGPT-discord-bot-main> pip install -r requirements.txt
Requirement already satisfied: discord.py==2.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (2.1.0)
Collecting openai==0.26.1
  Using cached openai-0.26.1.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-echs_nis\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-echs_nis\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-echs_nis\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-echs_nis\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1030: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

my python version is 3.11.1

**Comment by GustavRaispits** [comment]
It looks like there is an encoding issue with your Python version (3.11.1). Try updating to the latest version of Python. You can also try setting the environment variable PYTHONIOENCODING to UTF-8 before running the command.

**Comment by aW3ikun** [comment]
https://github.com/Zero6992/chatGPT-discord-bot/issues/120

**Comment by tonyleesos** [comment]
Finally, You have to downgrade to Python 3.10.I try to  setting the environment variable PYTHONIOENCODING to UTF-8 but It's not work.

**Comment by GustavRaispits** [comment]
> Finally, You have to downgrade to Python 3.10.I try to setting the environment variable PYTHONIOENCODING to UTF-8 but It's not work.

I'm glad I helped!
