### ISSUE TITLE
OSError ：can't connect discord

### ISSUE THREAD

**Issue by QiuZiXian** [Zero6992/chatGPT-discord-bot#135]
env：win10+python3.9+[chatGPT-discord-bot](https://github.com/Zero6992/chatGPT-discord-bot) latest

`
Initializing tokenizer...
Done
2023-02-03 14:07:50 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\e\project\shida\work\chat-group\chatGPT-discord-bot\main.py", line 29, in <module>
    bot.run_discord_bot()
  File "E:\e\project\shida\work\chat-group\chatGPT-discord-bot\src\bot.py", line 152, in run_discord_bot
    client.run(TOKEN)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\dell\anaconda3\envs\python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\client.py", line 580, in login
    data = await self.http.static_login(token)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\Users\dell\anaconda3\envs\python39\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]
`
please help，thanks.

**Comment by Zero6992** [comment]
Make sure the discord bot token you provided is correct

**Comment by eighttran** [comment]
2023-02-05 09:23:11 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/chatGPT-discord-bot/main.py", line 29, in <module>
    bot.run_discord_bot()
  File "/workspaces/chatGPT-discord-bot/src/bot.py", line 154, in run_discord_bot
    client.run(TOKEN)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
  File "/home/codespace/.python/current/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/codespace/.python/current/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 745, in start
    await self.login(token)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 580, in login
    data = await self.http.static_login(token)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
@eighttran ➜ /workspaces/chatGPT-discord-bot (main) $ 

Same problem , i try to reset token many time, still not working

**Comment by Zero6992** [comment]
Make sure you grab the "Token" from the "Bot" page in the Discord development site, rather than the "Secret" from the "General Information" page

**Comment by Zero6992** [comment]
Closing issue due to inactivity
