### ISSUE TITLE
help

### ISSUE THREAD

**Issue by WuChenDi** [Zero6992/chatGPT-discord-bot#152]
```bash
station :: /app/wudi/chatGPT-discord-bot ‹main*› » docker-compose up             
[+] Running 0/1
 ⠿ chatgpt-discord-bot Error                                                                                                                                                                             7.3s
[+] Building 2.7s (11/11) FINISHED                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                                     0.0s
 => => transferring dockerfile: 633B                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                        0.0s
 => => transferring context: 1.07kB                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:3.10-alpine                                                                                                                                    2.7s
 => [1/6] FROM docker.io/library/python:3.10-alpine@sha256:8bad2003880e7ef1d0cde5157ffdbc3d62caa3a8370981ffe74f6782e321bb55                                                                              0.0s
 => [internal] load build context                                                                                                                                                                        0.0s
 => => transferring context: 32.81kB                                                                                                                                                                     0.0s
 => CACHED [2/6] RUN apk add --update   build-base   cairo   cairo-dev   cargo   freetype-dev   gcc   gdk-pixbuf-dev   gettext   jpeg-dev   lcms2-dev   libffi-dev   musl-dev   openjpeg-dev   openssl-  0.0s
 => CACHED [3/6] RUN pip install cryptography                                                                                                                                                            0.0s
 => CACHED [4/6] COPY ./ /DiscordBot                                                                                                                                                                     0.0s
 => CACHED [5/6] WORKDIR /DiscordBot                                                                                                                                                                     0.0s
 => CACHED [6/6] RUN pip3 install -r requirements.txt                                                                                                                                                    0.0s
 => exporting to image                                                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                                                  0.0s
 => => writing image sha256:113715a6ad772bc4750cca2da6d2de7e94e07d204b66172d0719166a3af12a9f                                                                                                             0.0s
 => => naming to docker.io/library/chatgpt-discord-bot                                                                                                                                                   0.0s
[+] Running 1/0
 ⠿ Container chatgpt-discord-bot  Created                                                                                                                                                                0.0s
Attaching to chatgpt-discord-bot
chatgpt-discord-bot  | Traceback (most recent call last):
chatgpt-discord-bot  |   File "/DiscordBot/main.py", line 1, in <module>
chatgpt-discord-bot  |     from src import bot
chatgpt-discord-bot  |   File "/DiscordBot/src/bot.py", line 3, in <module>
chatgpt-discord-bot  |     from src import responses
chatgpt-discord-bot  |   File "/DiscordBot/src/responses.py", line 17, in <module>
chatgpt-discord-bot  |     config = get_config()
chatgpt-discord-bot  |   File "/DiscordBot/src/responses.py", line 12, in get_config
chatgpt-discord-bot  |     config = json.load(f)
chatgpt-discord-bot  |   File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
chatgpt-discord-bot  |     return loads(fp.read(),
chatgpt-discord-bot  |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
chatgpt-discord-bot  |     return _default_decoder.decode(s)
chatgpt-discord-bot  |   File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
chatgpt-discord-bot  |     raise JSONDecodeError("Extra data", s, end)
chatgpt-discord-bot  | json.decoder.JSONDecodeError: Extra data: line 6 column 1 (char 224)
chatgpt-discord-bot exited with code 1
```

**Comment by WuChenDi** [comment]
```bash
station :: /app/wudi/chatGPT-discord-bot ‹main*› » python3 main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src import bot
  File "/app/wudi/chatGPT-discord-bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/app/wudi/chatGPT-discord-bot/src/responses.py", line 17, in <module>
    config = get_config()
  File "/app/wudi/chatGPT-discord-bot/src/responses.py", line 12, in get_config
    config = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 6 column 1 (char 224)
```

**Comment by Zero6992** [comment]
Make sure your `config.json` looks like this
```
{
    "discord_bot_token":"",
    "discord_channel_id":"",
    "openAI_key": ""
}
```

**Comment by WuChenDi** [comment]
> Make sure your `config.json` looks like this
> 
> ```
> {
>     "discord_bot_token":"",
>     "discord_channel_id":"",
>     "openAI_key": ""
> }
> ```

Thanks for your reply, it's like this, in json format.

**Comment by Zero6992** [comment]
your environment and python version?

**Comment by WuChenDi** [comment]
It's amazing.
Now there is no more problem, I reformatted the `config.json` file and then ran it and it worked.
Best Regards
