### ISSUE TITLE
Bot started showing errors after restarting

### ISSUE THREAD

**Issue by Jan64X** [Zero6992/chatGPT-discord-bot#157]
It worked fine until now, no clue what caused this. Thanks in advance!
Here is the log: 

2023-02-07 22:45:27 ERROR    src.bot -> Error while sending starting prompt: That model does not exist
Traceback (most recent call last):
  File "C:\Users\petrl\Desktop\ChatZer0\src\bot.py", line 109, in send_start_prompt
    responseMessage = await responses.handle_response(prompt)
  File "C:\Users\petrl\Desktop\ChatZer0\src\responses.py", line 21, in handle_response
    response = await chatbot.ask(message)
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\Official.py", line 215, in ask
    completion = await self._get_completion(
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\Official.py", line 196, in _get_completion
    return await openai.Completion.acreate(
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 311, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 646, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\petrl\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist

**Comment by fizzym4d** [comment]
I'm getting the same error

**Comment by Reece10Penny** [comment]
2023-02-07 22:04:55 INFO     src.bot -> ReeceP#4529 : 'Hi' (fba)
2023-02-07 22:04:56 ERROR    src.bot -> Error while sending message: That model does not exist
Traceback (most recent call last):

I am getting this error.

Only the /Chat command is not working.

**Comment by Reece10Penny** [comment]
This is also the same error as above

**Comment by Max-Trueby** [comment]
same here

**Comment by Reece10Penny** [comment]
Somebody, please post a solution once it has been found.

**Comment by RaneyDazed** [comment]
Also having the same problem. Tried using a new api key from openai, made a new bot, rebuilt the whole thing and it kept giving me trouble :p It worked like a charm for about an hour tho which was nice!
using it via compose file on ubuntu 22.04

```elm
2023-02-07 22:27:22 INFO     src.bot -> ChatGPT#1813 is now running!
2023-02-07 22:34:27 INFO     src.bot -> Raneydazed#4277 : 'are you fucking fixed yet' (💬general)
2023-02-07 22:34:28 ERROR    src.bot -> Error while sending message: That model does not exist
Traceback (most recent call last):
  File "/DiscordBot/src/bot.py", line 32, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
  File "/DiscordBot/src/responses.py", line 21, in handle_response
    response = await chatbot.ask(message)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 215, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 196, in _get_completion
    return await openai.Completion.acreate(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 311, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 646, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
```

it appears that its not a new error. 
https://github.com/acheong08/ChatGPT/issues/600

**Comment by FuseFairy** [comment]
I guess  OpenAI has closed ChatGPT API again，I temporarily switching to using GPT-3 mode.

`async def handle_response_d(message) -> str:
    response = await sync_to_async(openai.Completion.create)(
        model="text-davinci-003",
        prompt=message,
        temperature=0.7,
        max_tokens=2048,
        top_p=1,
        frequency_penalty=0.0,
        presence_penalty=0.0,
    )
    responseMessage = response.choices[0].text`

**Comment by vinyl-umbrella** [comment]
Better to set environment variables with docker-compose than to rewrite python code

```
version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: chatgpt-discord-bot
    container_name: chatgpt-discord-bot
    environment:
        - GPT_ENGINE=text-davinci-003
    volumes:
      - ./config.json:/DiscordBot/config.json
```

**Comment by Huangxt57** [comment]
Could there be an automatic switch to the GPT-3 model when the ChatGPT API is not available?

**Comment by FuseFairy** [comment]
Simple modification looks like this:
```
async def handle_response(message) -> str:
    try:
        response = await sync_to_async(chatbot.ask)(message)
        responseMessage = response["choices"][0]["text"]
    except Exception:
            response = await sync_to_async(openai.Completion.create)(
                model="text-davinci-003",
                prompt=message,
                temperature=0.7,
                max_tokens=2048,
                top_p=1,
                frequency_penalty=0.0,
                presence_penalty=0.0,
            )
                
    responseMessage = response.choices[0].text

    return responseMessage
```

**Comment by FuseFairy** [comment]
Simple modification looks like this:
```
async def handle_response(message) -> str:
    try:
        response = await sync_to_async(chatbot.ask)(message)
        responseMessage = response["choices"][0]["text"]
    except Exception:
        response = await sync_to_async(openai.Completion.create)(
            model="text-davinci-003",
            prompt=message,
            temperature=0.7,
            max_tokens=2048,
            top_p=1,
            frequency_penalty=0.0,
            presence_penalty=0.0,
        )
                
        responseMessage = response.choices[0].text

    return responseMessage
```

**Comment by FuseFairy** [comment]
> Could there be an automatic switch to the GPT-3 model when the ChatGPT API is not available?

Simple modification looks like this:
```
async def handle_response(message) -> str:
    try:
        response = await sync_to_async(chatbot.ask)(message)
        responseMessage = response["choices"][0]["text"]
    except Exception:
        response = await sync_to_async(openai.Completion.create)(
            model="text-davinci-003",
            prompt=message,
            temperature=0.7,
            max_tokens=2048,
            top_p=1,
            frequency_penalty=0.0,
            presence_penalty=0.0,
        )          
        responseMessage = response.choices[0].text

    return responseMessage
```

**Comment by Zero6992** [comment]
https://github.com/acheong08/ChatGPT/issues/590

OpenAI shut down ChatGPT model, but it works again now

**Comment by Reece10Penny** [comment]
Mine is still down
