### ISSUE TITLE
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

### ISSUE THREAD

**Issue by Zero6992** [Zero6992/chatGPT-discord-bot#160]
looking into it
```
Traceback (most recent call last):
  File "/Users/mirtris/Desktop/github/chatGPT-discord-bot/src/bot.py", line 32, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
  File "/Users/mirtris/Desktop/github/chatGPT-discord-bot/src/responses.py", line 21, in handle_response
    response = await chatbot.ask(message)
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/revChatGPT/Official.py", line 215, in ask
    completion = await self._get_completion(
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/revChatGPT/Official.py", line 196, in _get_completion
    return await openai.Completion.acreate(
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 311, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 646, in _interpret_async_response
    self._interpret_response_line(
  File "/Users/mirtris/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 663, in _interpret_response_line
    raise error.ServiceUnavailableError(
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
```
```
openai.error.RateLimitError: The server is currently overloaded with other requests. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists
```

**Comment by RedSnoww12** [comment]
Your bot can send the `starting-prompt.txt` ?

My error when it send the starting message : 
```
2023-02-08 11:35:53 INFO     src.bot -> Send starting prompt with size 11
2023-02-08 11:36:32 ERROR    src.bot -> Error while sending starting prompt: The server is overloaded or not ready yet.
[...]
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
2023-02-08 11:36:33 INFO     src.bot -> M. GPT is now running!
```

Try to send the `starting-prompt.txt`

**Comment by Cellenseres** [comment]
@Zero6992 is it because your bot is using "text-chat-davinci-002-20221122"?
Something happened to that model which causes your Bot to not work anymore.
Yesterday, for ~an hour, the model didn't exist anymore. Then, it existed again but since then, it's either overloaded or not ready.

**Comment by Zero6992** [comment]
> @Zero6992 is it because your bot is using "text-chat-davinci-002-20221122"? Something happened to that model which causes your Bot to not work anymore. Yesterday, for ~an hour, the model didn't exist anymore. Then, it existed again but since then, it's either overloaded or not ready.

Not likely

Based on this discussion, the model was overloaded by somebody's discord bot with 1M users

https://github.com/acheong08/ChatGPT/issues/607

 I am considering switching back to the GPT-3 model, which requires payment

**Comment by Jasmine-liang** [comment]
Would like to try the GPT-3 model :)

**Comment by Zero6992** [comment]
Temporarily switching to the GPT-3 model
