### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by TaijiMonster** [Zero6992/chatGPT-discord-bot#164]
2023-02-08T23:03:18.119922467Z [2023-02-08 23:03:18] [INFO    ] discord.client: logging in using static token
2023-02-08T23:03:19.467471212Z Traceback (most recent call last):
2023-02-08T23:03:19.467492722Z   File "/DiscordBot/main.py", line 29, in <module>
2023-02-08T23:03:19.467507123Z     bot.run_discord_bot()
2023-02-08T23:03:19.467516140Z   File "/DiscordBot/src/bot.py", line 212, in run_discord_bot
2023-02-08T23:03:19.467665091Z     client.run(TOKEN)
2023-02-08T23:03:19.467671343Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 828, in run
2023-02-08T23:03:19.467818979Z     asyncio.run(runner())
2023-02-08T23:03:19.467825511Z   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-02-08T23:03:19.467868921Z     return loop.run_until_complete(main)
2023-02-08T23:03:19.467872408Z   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-02-08T23:03:19.467977246Z     return future.result()
2023-02-08T23:03:19.467982747Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 817, in runner
2023-02-08T23:03:19.468107599Z     await self.start(token, reconnect=reconnect)
2023-02-08T23:03:19.468112378Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
2023-02-08T23:03:19.468207377Z     await self.connect(reconnect=reconnect)
2023-02-08T23:03:19.468211515Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
2023-02-08T23:03:19.468286527Z     raise PrivilegedIntentsRequired(exc.shard_id) from None
2023-02-08T23:03:19.468290815Z discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by jacket430** [comment]
It's broken for me, but I'm pretty sure mine is an API issue. It looks like you forgot to enable the required intents at the link in that log.

**Comment by tplesetz** [comment]
In the linked url, manage the bot settings of your discord application and make sure that the following setting is enabled:

![image](https://user-images.githubusercontent.com/12537305/217678776-1c3b9fda-14ff-4fd4-9070-402053dc176b.jpeg)

This is referenced in the readme file as well
