### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by 21072002hung** [Zero6992/chatGPT-discord-bot#169]
src.bot -> Error while sending message: The server had an error while processing your request. Sorry about that!
Traceback (most recent call last):
  File "C:\Project\chatGPT-discord-bot-0.7.1\src\bot.py", line 31, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\chatGPT-discord-bot-0.7.1\src\responses.py", line 7, in handle_response
    response = await sync_to_async(openai.Completion.create)(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mobanight2107\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

**Comment by Zero6992** [comment]
This is an issue with the OpenAI server, retrying should resolve it

**Comment by Zero6992** [comment]
Closing issue due to inactivity
