### ISSUE TITLE
ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by mMONTAGEe** [Zero6992/chatGPT-discord-bot#170]
Traceback (most recent call last):
  File "C:\Users\xxx\OneDrive\Documents\chatGPT-discord-bot-main\main.py", line 1, in <module>
    from src import bot
  File "C:\Users\xxx\OneDrive\Documents\chatGPT-discord-bot-main\src\bot.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

python3.10

**Comment by mMONTAGEe** [comment]
i forgot to install discord.py
