### ISSUE TITLE
openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by HaKLMTT** [Zero6992/chatGPT-discord-bot#181]
Run python main with the latest code, the following error is thown:

[2023-02-12 07:24:00] [INFO    ] discord.client: logging in using static token
[2023-02-12 07:24:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bc114565b33a0c44370d962a518e9fcc).
2023-02-12 07:24:04 INFO     src.bot -> Send starting prompt with size 11
2023-02-12 07:24:04 ERROR    src.bot -> Error while sending starting prompt: That model does not exist
Traceback (most recent call last):
  File "/root/git/chatGPT-discord-bot/src/bot.py", line 108, in send_start_prompt
    responseMessage = await responses.handle_response(prompt)
  File "/root/git/chatGPT-discord-bot/src/responses.py", line 11, in handle_response
    response = await chatbot.ask(message)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 232, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 213, in _get_completion
    return await openai.Completion.acreate(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 310, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 645, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
2023-02-12 07:24:05 INFO     src.bot -> ChatBoy#0037 is now running!

**Comment by HaKLMTT** [comment]
Does it mean that I must pay for the chatgpt api?

**Comment by Zero6992** [comment]
Can you provide the contents of your `.env` file?

**Comment by HaKLMTT** [comment]
Something like the following:
DISCORD_BOT_TOKEN="MTA3MzQ0ODk3ODg2MTAxOTIxNg.............UnS4lWkGBq70"
OPENAI_KEY="sk-FhGzEQNAFVz...............PFZ319tvJU"
DISCORD_CHANNEL_ID="10735250.........894352"

One more info:
two days ago, when using the GPT-3 version api, anything is OK.

**Comment by HaKLMTT** [comment]
Thanks, I find the reason according to your question?
