### ISSUE TITLE
Openai error or code error?

### ISSUE THREAD

**Issue by TaijiMonster** [Zero6992/chatGPT-discord-bot#182]
2023-02-12T10:52:27.070324467Z 2023-02-12 10:52:27 ERROR    src.bot -> Error while sending message: The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. {
2023-02-12T10:52:27.070343863Z   "error": {
2023-02-12T10:52:27.070346578Z     "message": "The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.",
2023-02-12T10:52:27.070348592Z     "type": "server_error",
2023-02-12T10:52:27.070350185Z     "param": null,
2023-02-12T10:52:27.070351688Z     "code": null
2023-02-12T10:52:27.070353361Z   }
2023-02-12T10:52:27.070355375Z }
2023-02-12T10:52:27.070358761Z  500 {'error': {'message': 'The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.', 'type': 'server_error', 'param': None, 'code': None}} <CIMultiDictProxy('Date': 'Sun, 12 Feb 2023 10:52:26 GMT', 'Content-Type': 'application/json', 'Content-Length': '292', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Model': 'text-davinci-003', 'Openai-Organization': 'user-buoysbt1llsrurj8bxfujqtj', 'Openai-Processing-Ms': '30225', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Request-Id': '96d650456bb194e33c7177487a594807')>
2023-02-12T10:52:27.070362899Z Traceback (most recent call last):
2023-02-12T10:52:27.070364562Z   File "/DiscordBot/src/bot.py", line 31, in send_message
2023-02-12T10:52:27.070366145Z     response = f"{response}{await responses.handle_response(user_message)}"
2023-02-12T10:52:27.070367798Z   File "/DiscordBot/src/responses.py", line 11, in handle_response
2023-02-12T10:52:27.070369441Z     response = await chatbot.ask(message)
2023-02-12T10:52:27.070370864Z   File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 232, in ask
2023-02-12T10:52:27.070372607Z     completion = await self._get_completion(
2023-02-12T10:52:27.070374050Z   File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 213, in _get_completion
2023-02-12T10:52:27.070380442Z     return await openai.Completion.acreate(
2023-02-12T10:52:27.070382035Z   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 45, in acreate
2023-02-12T10:52:27.070383488Z     return await super().acreate(*args, **kwargs)
2023-02-12T10:52:27.070385201Z   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
2023-02-12T10:52:27.070386603Z     response, _, api_key = await requestor.arequest(
2023-02-12T10:52:27.070387846Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 310, in arequest
2023-02-12T10:52:27.070389188Z     resp, got_stream = await self._interpret_async_response(result, stream)
2023-02-12T10:52:27.070390421Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 645, in _interpret_async_response
2023-02-12T10:52:27.070391713Z     self._interpret_response_line(
2023-02-12T10:52:27.070392925Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
2023-02-12T10:52:27.070394268Z     raise self.handle_error_response(
2023-02-12T10:52:27.070395480Z openai.error.APIError: The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. {
2023-02-12T10:52:27.070396893Z   "error": {
2023-02-12T10:52:27.070398315Z     "message": "The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.",
2023-02-12T10:52:27.070399798Z     "type": "server_error",
2023-02-12T10:52:27.070401051Z     "param": null,
2023-02-12T10:52:27.070402313Z     "code": null
2023-02-12T10:52:27.070403515Z   }
2023-02-12T10:52:27.070404667Z }
2023-02-12T10:52:27.070405880Z  500 {'error': {'message': 'The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.', 'type': 'server_error', 'param': None, 'code': None}} <CIMultiDictProxy('Date': 'Sun, 12 Feb 2023 10:52:26 GMT', 'Content-Type': 'application/json', 'Content-Length': '292', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Model': 'text-davinci-003', 'Openai-Organization': 'user-buoysbt1llsrurj8bxfujqtj', 'Openai-Processing-Ms': '30225', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Request-Id': '96d650456bb194e33c7177487a594807')>

**Comment by TaijiMonster** [comment]
using python3 main.py is working

**Comment by Zero6992** [comment]
python version need to  >= 3.9
