### ISSUE TITLE
Error: Something went wrong, please try again later 

### ISSUE THREAD

**Issue by kit8379** [Zero6992/chatGPT-discord-bot#186]
I only reply a small word but it told me exceed content limit?

```
2023-02-17 10:36:23 ERROR    src.bot -> Error while sending message: This model's maximum context length is 2049 tokens, however you requested 4000 tokens (71 in your prompt; 3929 for the completion). Please reduce your prompt; or completion length.
Traceback (most recent call last):
  File "/home/container/src/bot.py", line 31, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/src/responses.py", line 11, in handle_response
    response = await chatbot.ask(message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/revChatGPT/Official.py", line 232, in ask
    completion = await self._get_completion(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/revChatGPT/Official.py", line 213, in _get_completion
    return await openai.Completion.acreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 310, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 645, in _interpret_async_response
    self._interpret_response_line(
  File "/home/container/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 2049 tokens, however you requested 4000 tokens (71 in your prompt; 3929 for the completion). Please reduce your prompt; or completion length.
```

**Comment by Zero6992** [comment]
old version issue
