### ISSUE TITLE
Error: Something went wrong, please try again later!(openai issue)

### ISSUE THREAD

**Issue by mu-bibai** [Zero6992/chatGPT-discord-bot#193]
Maybe there is some problem when communicate with openai api?

![image](https://user-images.githubusercontent.com/69948498/220279445-f9571e21-24fe-4485-8e55-b52967896ed4.png)
2023-02-21 02:28:30 INFO     src.bot -> mubibai#2103 : 'introduce yourself' (chat-gpt)
2023-02-21 02:28:37 ERROR    src.bot -> Error while sending message: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} <CIMultiDictProxy('Date': 'Tue, 21 Feb 2023 07:28:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'c73110fc90ac8b811610e51b8dead212', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains')>
Traceback (most recent call last):
  File "/root/discord/bot/chatGPT-discord-bot/src/bot.py", line 31, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
  File "/root/discord/bot/chatGPT-discord-bot/src/responses.py", line 11, in handle_response
    response = await chatbot.ask(message)
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/Official.py", line 232, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/Official.py", line 213, in _get_completion
    return await openai.Completion.acreate(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 310, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 645, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} <CIMultiDictProxy('Date': 'Tue, 21 Feb 2023 07:28:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'c73110fc90ac8b811610e51b8dead212', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains')>

**Comment by TKWS239** [comment]
Same issue here

**Comment by TKWS239** [comment]
Issue is solved due to the OpenAI currently have server issue, please refer to this link 
https://status.openai.com/
