### ISSUE TITLE
Issue after updating to the last versión with type Object Completion

### ISSUE THREAD

**Issue by pjpmosteiro** [Zero6992/chatGPT-discord-bot#200]
```
2023-02-23 14:12:38 INFO     discord.client logging in using static token
2023-02-23 14:12:39 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: xxxxx).
2023-02-23 14:12:41 INFO     src.bot -> Send starting prompt with size 11
2023-02-23 14:12:41 ERROR    src.bot -> Error while sending starting prompt: type object 'Completion' has no attribute 'acreate'
Traceback (most recent call last):
  File "/root/chatGPT-discord-bot/src/bot.py", line 108, in send_start_prompt
    responseMessage = await responses.handle_response(prompt)
  File "/root/chatGPT-discord-bot/src/responses.py", line 11, in handle_response
    response = await chatbot.ask(message)
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/Official.py", line 232, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/Official.py", line 213, in _get_completion
    return await openai.Completion.acreate(
AttributeError: type object 'Completion' has no attribute 'acreate'
2023-02-23 14:12:41 INFO     src.bot -> xxxx#xxxx is now running!`
```

I just updated my bot to the last version of the git repo and now I get this error. Env Ubuntu 22.10 server, no Docker, launched straight up with python3 main.py

**Comment by Alt3rnativity** [comment]
I was able to fix this by updating the src/responses.py to this:
`openAI_key = os.getenv("OPENAI_KEY")
openAI_model = os.getenv("ENGINE")

openai.api_key = "###############################"

async def handle_response(message) -> str:
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt=message,
        temperature=0.7,
        max_tokens=2048,
        top_p=1,
        frequency_penalty=0.0,
        presence_penalty=0.0,
    )          
    responseMessage = response.choices[0].text

    return responseMessage`

**Comment by hubertdungen** [comment]
same here!

**Comment by Zero6992** [comment]
Old version issue
