### ISSUE TITLE
openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by helsan74** [Zero6992/chatGPT-discord-bot#216]
Using Version 1.0.1
Works when running: python3 main.py
Give this error when using docker with newly created container

2023-03-03T08:09:20.964946431Z 2023-03-03 08:09:20 INFO     src.bot -> User#2199 : 'What are your limits?' (chatgpt)
2023-03-03T08:09:21.796517390Z 2023-03-03 08:09:21 ERROR    src.bot -> Error while sending message: That model does not exist
2023-03-03T08:09:21.796567250Z Traceback (most recent call last):
2023-03-03T08:09:21.796574848Z   File "/DiscordBot/src/bot.py", line 31, in send_message
2023-03-03T08:09:21.796608369Z     response = f"{response}{await responses.handle_response(user_message)}"
2023-03-03T08:09:21.796615580Z   File "/DiscordBot/src/responses.py", line 11, in handle_response
2023-03-03T08:09:21.796637281Z     response = await chatbot.ask(message)
2023-03-03T08:09:21.796645341Z   File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 232, in ask
2023-03-03T08:09:21.796650665Z     completion = await self._get_completion(
2023-03-03T08:09:21.796655486Z   File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 213, in _get_completion
2023-03-03T08:09:21.796660421Z     return await openai.Completion.acreate(
2023-03-03T08:09:21.796665128Z   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 45, in acreate
2023-03-03T08:09:21.796669981Z     return await super().acreate(*args, **kwargs)
2023-03-03T08:09:21.796674696Z   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
2023-03-03T08:09:21.796679577Z     response, _, api_key = await requestor.arequest(
2023-03-03T08:09:21.796684235Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 310, in arequest
2023-03-03T08:09:21.796689089Z     resp, got_stream = await self._interpret_async_response(result, stream)
2023-03-03T08:09:21.796693925Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 645, in _interpret_async_response
2023-03-03T08:09:21.796698807Z     self._interpret_response_line(
2023-03-03T08:09:21.796718223Z   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
2023-03-03T08:09:21.796724735Z     raise self.handle_error_response(
2023-03-03T08:09:21.796729650Z openai.error.InvalidRequestError: That model does not exist

**Comment by helsan74** [comment]
revChatGPT==3.0.5

**Comment by Zero6992** [comment]
check your `.env` file 

`OPENAI_ENGINE="gpt-3.5-turbo"`

**Comment by helsan74** [comment]
# Optional setting
CHAT_MODEL="UNOFFICIAL"
OPENAI_ENGINE="gpt-3.5-turbo"
LOGGING="True"
REPLY_ALL="False"

**Comment by Zero6992** [comment]
you sure you are using Version 1.0.1?

In the error message, `responses.handle_response` is no longer exists in Version 1.0.1

`2023-03-03T08:09:21.796608369Z response = f"{response}{await responses.handle_response(user_message)}"`

**Comment by helsan74** [comment]
If I revert to OFFICIAL model and use python3 main.py it works
But when in docker it's does one post and then error

**Comment by helsan74** [comment]
> you sure you are using Version 1.0.1?
> 
> In the error message, `responses.handle_response` is no longer exists in Version 1.0.1
> 
> `2023-03-03T08:09:21.796608369Z response = f"{response}{await responses.handle_response(user_message)}"`

I erased the folder... and redeployed from scratch 
root@vps123:~/chatGPT-discord-bot-1.0.1# ls -l
total 56
-rw-r--r-- 1 root root  2149 Mar  3 08:29 chatgpt_discord_bot.log
-rw-rw-r-- 1 root root   157 Mar  3 06:22 docker-compose.yml
-rw-rw-r-- 1 root root   733 Mar  3 06:22 Dockerfile
-rw-r--r-- 1 root root     0 Mar  3 08:09 Error
-rw-rw-r-- 1 root root 18092 Mar  3 06:22 LICENSE
-rw-rw-r-- 1 root root  1150 Mar  3 06:22 main.py
-rw-rw-r-- 1 root root  4365 Mar  3 06:22 README.md
-rw-rw-r-- 1 root root    58 Mar  3 06:22 requirements.txt
drwxrwxr-x 3 root root  4096 Mar  3 08:02 src
-rw-rw-r-- 1 root root    11 Mar  3 06:22 starting-prompt.txt

**Comment by Zero6992** [comment]
`docker-compose up --remove-orphans` and `docker compose up` again

**Comment by helsan74** [comment]
docker-compose up --remove-orphans
Recreating chatgpt-discord-bot ... done
Attaching to chatgpt-discord-bot
chatgpt-discord-bot    | [2023-03-03 08:41:35] [INFO    ] discord.client: logging in using static token
chatgpt-discord-bot    | Traceback (most recent call last):
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
chatgpt-discord-bot    |     data = await self.request(Route('GET', '/users/@me'))
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 744, in request
chatgpt-discord-bot    |     raise HTTPException(response, data)
chatgpt-discord-bot    | discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
chatgpt-discord-bot    | 
chatgpt-discord-bot    | The above exception was the direct cause of the following exception:
chatgpt-discord-bot    | 
chatgpt-discord-bot    | Traceback (most recent call last):
chatgpt-discord-bot    |   File "/DiscordBot/main.py", line 30, in <module>
chatgpt-discord-bot    |     bot.run_discord_bot()
chatgpt-discord-bot    |   File "/DiscordBot/src/bot.py", line 212, in run_discord_bot
chatgpt-discord-bot    |     client.run(TOKEN)
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 828, in run
chatgpt-discord-bot    |     asyncio.run(runner())
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
chatgpt-discord-bot    |     return loop.run_until_complete(main)
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
chatgpt-discord-bot    |     return future.result()
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 817, in runner
chatgpt-discord-bot    |     await self.start(token, reconnect=reconnect)
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 745, in start
chatgpt-discord-bot    |     await self.login(token)
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 580, in login
chatgpt-discord-bot    |     data = await self.http.static_login(token)
chatgpt-discord-bot    |   File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 805, in static_login
chatgpt-discord-bot    |     raise LoginFailure('Improper token has been passed.') from exc
chatgpt-discord-bot    | discord.errors.LoginFailure: Improper token has been passed.

**Comment by Zero6992** [comment]
Do you provide the correct Discord bot token?

**Comment by Zero6992** [comment]
It seems error occurred when login to your discord bot

**Comment by helsan74** [comment]
Yes because when I use the python3 main.py it shows up in the channel: Hello! How can I assist you today?
But whenever I use the docker I get an error

**Comment by helsan74** [comment]
Here's the results when using python3 main.py

2023-03-03 08:52:50 INFO     discord.client logging in using static token
2023-03-03 08:52:50,938 - discord.client - INFO - login - logging in using static token
2023-03-03 08:52:51 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: ea9b3xxxx).
2023-03-03 08:52:51,426 - discord.gateway - INFO - received_message - Shard ID None has connected to Gateway (Session ID: ea9b3xxxxx).
2023-03-03 08:52:53 INFO     src.bot -> Send starting prompt with size 11
2023-03-03 08:52:53,437 - src.bot - INFO - send_start_prompt - Send starting prompt with size 11
2023-03-03 08:52:54 INFO     src.bot -> Starting prompt response:Hello there! How can I assist you today?
2023-03-03 08:52:54,339 - src.bot - INFO - send_start_prompt - Starting prompt response:Hello there! How can I assist you today?
2023-03-03 08:52:54 INFO     src.bot -> BotAI#2743 is now running!
2023-03-03 08:52:54,511 - src.bot - INFO - on_ready - BotAI#2743 is now running!

**Comment by Zero6992** [comment]
Deleting the docker image and running `docker compose up` again

**Comment by helsan74** [comment]
No errors! Looks good now!
Thanks
