### ISSUE TITLE
OpenAIAuth.Error

### ISSUE THREAD

**Issue by merlin7vv4** [Zero6992/chatGPT-discord-bot#217]
Using : Python 3.11.0
            Pip:23.0.1
i have install requirements.

I have this error when i run on python:

PS D:\chatGPT-discord-bot> python -u "d:\chatGPT-discord-bot\main.py"
Traceback (most recent call last):
  File "d:\chatGPT-discord-bot\main.py", line 1, in <module>
    from src import bot
  File "d:\chatGPT-discord-bot\src\bot.py", line 4, in <module>
    from src import responses
  File "d:\chatGPT-discord-bot\src\responses.py", line 13, in <module>
    unofficial_chatbot = AsyncChatbot(config={"email":openAI_email, "password":openAI_password, "session_token":session_token})
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 701, in __init__
    super().__init__(
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 206, in __init__
    self.__check_credentials()
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 233, in __check_credentials
    raise error
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 231, in __check_credentials
    self.__login()
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 371, in __login
    auth.begin()
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "C:\Users\merlin\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAuth.py", line 210, in __part_four
    raise Error(
OpenAIAuth.Error

**Comment by merlin7vv4** [comment]
my
