### ISSUE TITLE
Leaving out authentication for the unofficial API prevents the bot from running

### ISSUE THREAD

**Issue by NachoPicchu** [Zero6992/chatGPT-discord-bot#218]
Leaving out the openAI email/password/session token in .env results in 

```
Traceback (most recent call last):
  File "./main.py", line 1, in <module>
    from src import bot
  File "/home/user/chatgptbot/chatGPT-discord-bot/src/bot.py", line 4, in <module>
    from src import responses
  File "/home/user/chatgptbot/chatGPT-discord-bot/src/responses.py", line 13, in <module>
    unofficial_chatbot = AsyncChatbot(config={"email":openAI_email, "password":openAI_password, "session_token":session_token})
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 701, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 206, in __init__
    self.__check_credentials()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 231, in __check_credentials
    self.__login()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 364, in __login
    auth.get_access_token()
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 318, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'

```
completely removing the definition of `unofficial_handle_response`  and the parsing of the relevant vairables in responses.py fixes this (for my use-case).

**Comment by Zero6992** [comment]
fixed in here https://github.com/Zero6992/chatGPT-discord-bot/commit/9b0cbe083a004382e44e39b3a84a34f60e77de47
