### ISSUE TITLE
Can not run python3 main.py, pls help me!

### ISSUE THREAD

**Issue by Ndh474** [Zero6992/chatGPT-discord-bot#226]
Traceback (most recent call last):
  File "D:\Download\chatGPT-discord-bot-main\main.py", line 1, in <module>
    from src import bot
  File "D:\Download\chatGPT-discord-bot-main\src\bot.py", line 4, in <module>
    from src import responses
  File "D:\Download\chatGPT-discord-bot-main\src\responses.py", line 1, in <module>
    from revChatGPT.V1 import AsyncChatbot
ModuleNotFoundError: No module named 'revChatGPT.V1'

**Comment by frorayz** [comment]
#222 Please look at the issues before. Make sure you are using python 3.10

**Comment by GeboArt** [comment]
You must make sure that you have installed the indicated module.
In the terminal run the following command:

`pip install revChatGPT`

If you're having trouble, run it like this:

`pip install --user revChatGPT`
