### ISSUE TITLE
Cannot run the bot

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#227]
Getting this error, not sure what its about. I tried changing machine and the account itself but not working.

```
2023-03-07 04:04:19 ERROR    src.bot -> Error while sending starting prompt: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
Traceback (most recent call last):
  File "/home/rayz/xxx/src/bot.py", line 110, in send_start_prompt
    response = f"{response}{await responses.unofficial_handle_response(prompt)}"
  File "/home/rayz/xxx/src/responses.py", line 23, in unofficial_handle_response
    async for response in unofficial_chatbot.ask(message):
  File "/home/rayz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 803, in ask
    self.__check_response(response)
  File "/home/rayz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 917, in __check_response
    response.raise_for_status()
  File "/home/rayz/.local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
```

**Comment by frorayz** [comment]
https://github.com/acheong08/ChatGPT/issues/1064

Never mind updating the requirement and setting the version to latest fixed it.

**Comment by Zero6992** [comment]
updated `requirements.txt`
