### ISSUE TITLE
'Interaction' object has no attribute 'author'

### ISSUE THREAD

**Issue by R0MaNbI4** [Zero6992/chatGPT-discord-bot#230]
I start the bot, it starts, gives a welcome message, but at the first request it crashes with an error

Python 3.10.9
CHAT_MODEL="UNOFFICIAL"

What could be the problem? Am I misconfiguring something or is it a bot error?

```
C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot>python main.py
[2023-03-07 23:15:50] [INFO    ] discord.client: logging in using static token
[2023-03-07 23:15:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5f6329f1b20aea3522f574c0159a25d0).
←[30;1m2023-03-07 23:15:54←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> Send starting prompt with size 11
←[30;1m2023-03-07 23:16:17←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> Starting prompt response:Hello! How can I assist you today?
←[30;1m2023-03-07 23:16:18←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> chatGPT#2005 is now running!
←[30;1m2023-03-07 23:16:37←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> ←[31m[A]ngry Orang[E]#1990←[0m : 'are you working?' (основной)
[2023-03-07 23:16:37] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot\src\bot.py", line 147, in chat
    await send_message(interaction, user_message)
  File "C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot\src\bot.py", line 26, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'
```

**Comment by R0MaNbI4** [comment]
in the previous post I'm on the last commit `79885315621ed24c911527fcf41a1397421b3c1d`

if i roll back to the previous one before updating revChatGPT `b7af4a1e6e411615e96689be989f9bbd1ac4f906` then I get another error, which is more like errors from the openAI side (unofficial API not working anymore?):
```
C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot>python main.py
[2023-03-07 23:28:20] [INFO    ] discord.client: logging in using static token
[2023-03-07 23:28:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: effc811e172862e229c99fd974bd6a2c).
←[30;1m2023-03-07 23:28:24←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> Send starting prompt with size 11
←[30;1m2023-03-07 23:28:24←[0m ←[31mERROR   ←[0m ←[35msrc.bot←[0m -> Error while sending starting prompt: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
←[31mTraceback (most recent call last):
  File "C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot\src\bot.py", line 110, in send_start_prompt
    response = f"{response}{await responses.unofficial_handle_response(prompt)}"
  File "C:\Users\User\Desktop\discord_bot\chatGPT-discord-bot\src\responses.py", line 23, in unofficial_handle_response
    async for response in unofficial_chatbot.ask(message):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 803, in ask
    self.__check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 917, in __check_response
    response.raise_for_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403←[0m
←[30;1m2023-03-07 23:28:24←[0m ←[34;1mINFO    ←[0m ←[35msrc.bot←[0m -> chatGPT#2005 is now running!
```

**Comment by Zero6992** [comment]
The error says your connection has been banned by OpenAI

Please make sure you are not in a restricted area or using a VPN

**Comment by R0MaNbI4** [comment]
> For the **'Interaction' object has no attribute 'author'** error, you can check your .env file for the REPLYING_ALL option. The option name is changed from REPLY_ALL to REPLYING_ALL in the latest version which may cause the issue.

no, I didn't use this option

**Comment by R0MaNbI4** [comment]
> The error says your connection has been banned by OpenAI
> 
> Please make sure you are not in a restricted area or using a VPN

I tried changing account, browser and VPN, but it still doesn't work. It's strange that everything worked fine before, it seems, just before March 3, when they gave access to the normal API.

But I’ll try to deploy the application not on my computer, but on a remote hosting (probably free VPN in the browser is not so reliable)

**Comment by Arusina** [comment]
If I leave the REPLYING_ALL parameter empty, I get the same error message.

so with REPLYING_ALL=""
if I enter REPLYING_ALL="False" everything works fine

**Comment by walteij** [comment]
> The error says your connection has been banned by OpenAI
> 
> Please make sure you are not in a restricted area or using a VPN

I'm guessing running this bot in an Azure Container Instance counts as a restricted area then.....

**Comment by Zero6992** [comment]
> I'm guessing running this bot in an Azure Container Instance counts as a restricted area then.....

If you're using UNOFFICIAL model, it will bypass the cloudflare protection of the chatGPT through another proxy. You may be rejected by that proxy. Now I would recommend using the official model, which is more stable and not easy to use over a month’s free quota

**Comment by lintangtimur** [comment]
i have same error as above, and I added 1 line to `.env` and bot run fine
this my env
```
DISCORD_BOT_TOKEN="xxx"
OPENAI_EMAIL="xxx"
OPENAI_PASSWORD="xx"
SESSION_TOKEN="xxx"
DISCORD_CHANNEL_ID="xxxx"
LOGGING="True"
CHAT_MODEL="UNOFFICIAL"
REPLYING_ALL="False"
```

**Comment by alpturkay** [comment]
I am using the official API and I get the same error.

2023-03-16 11:12:08 INFO     src.bot -> artibo#8913 : /chat [How to make a discord bot?] in (<PartialMessageable id=1085632439038255156 type=<ChannelType.private: 1>>)
[2023-03-16 11:12:08] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/DiscordBot/src/bot.py", line 155, in chat
    await send_message(interaction, message)
  File "/DiscordBot/src/bot.py", line 30, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by alpturkay** [comment]
I am using the official api and having the same problem.

2023-03-16 11:12:08 INFO     src.bot -> art#8913 : /chat [How to make a discord bot?] in (<PartialMessageable id=1085632439038255156 type=<ChannelType.private: 1>>)
[2023-03-16 11:12:08] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/DiscordBot/src/bot.py", line 155, in chat
    await send_message(interaction, message)
  File "/DiscordBot/src/bot.py", line 30, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by alpturkay** [comment]
@KimGeunUk thanks! erasing all "" in .env solved the problem
