### ISSUE TITLE
Error : Too many requests

### ISSUE THREAD

**Issue by TheRebo** [Zero6992/chatGPT-discord-bot#238]
Hmmm what is this?, even though I'm using a new account and don't really use chatgpt on the website so it's impossible for too many requests.

Error while sending message: Error: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
Traceback (most recent call last):
  File "/home/kali/chatGPT-discord-bot/src/bot.py", line 31, in send_message
    response = f"{response}{await responses.official_handle_response(user_message)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/chatGPT-discord-bot/src/responses.py", line 20, in official_handle_response
    return offical_chatbot.ask(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/V3.py", line 194, in ask
    full_response: str = "".join(response)
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/V3.py", line 151, in ask_stream
    raise Exception(
Exception: Error: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by frorayz** [comment]
> Hmmm what is this?, even though I'm using a new account and don't really use chatgpt on the website so it's impossible for too many requests.
> 
> Error while sending message: Error: 429 Too Many Requests { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } } Traceback (most recent call last): File "/home/kali/chatGPT-discord-bot/src/bot.py", line 31, in send_message response = f"{response}{await responses.official_handle_response(user_message)}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/kali/chatGPT-discord-bot/src/responses.py", line 20, in official_handle_response return offical_chatbot.ask(message) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/revChatGPT/V3.py", line 194, in ask full_response: str = "".join(response) ^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/revChatGPT/V3.py", line 151, in ask_stream raise Exception( Exception: Error: 429 Too Many Requests { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

You either ran out of free credits and probably using old account session token's login. Check your .env and re populate with new account token's email + pass
