### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by chroniclex** [Zero6992/chatGPT-discord-bot#239]
I just started receiving this today. Is there an issue with the API site?

2023-03-08 11:36:17 ERROR    src.bot -> Error while sending message: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
Traceback (most recent call last):
  File "/home/user/chatGPT-discord-bot/src/bot.py", line 35, in send_message
    response = f"{response}{await responses.unofficial_handle_response(user_message)}"
  File "/home/user/chatGPT-discord-bot/src/responses.py", line 25, in unofficial_handle_response
    async for response in unofficial_chatbot.ask(message):
  File "/home/user/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 813, in ask
    self.__check_response(response)
  File "/home/user/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 927, in __check_response
    response.raise_for_status()
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403

**Comment by shinysocks** [comment]
make sure you're using the correct version of revChatGPT in requirements.txt. I also encountered this error with an older version.
![image](https://user-images.githubusercontent.com/91911303/223878180-93b6d9e0-0b94-4cfc-b276-29273a7028d4.png)

(this is just my first guess, lemme know if that doesn't resolve the issue)

**Comment by chroniclex** [comment]
yeah I was on revChatGPT 3.1.5, I ran an upgrade to 3.1.8.2 and modified the requirements and still experienced the same error.

**Comment by frorayz** [comment]
> yeah I was on revChatGPT 3.1.5, I ran an upgrade to 3.1.8.2 and modified the requirements and still experienced the same error.

[V1 is dead](https://github.com/acheong08/ChatGPT/issues/1082). He is finding other ways to bypass the api but for now you have to use the official one.

**Comment by Zero6992** [comment]
Unofficial is unsupported anymore
