### ISSUE TITLE
Can not run bot

### ISSUE THREAD

**Issue by pinganyiye** [Zero6992/chatGPT-discord-bot#248]
I typed python3 main.py and it said blow error，who can help me, txs

Traceback (most recent call last):
  File "/data/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/data/chatGPT-discord-bot/src/bot.py", line 6, in <module>
    from src import responses
  File "/data/chatGPT-discord-bot/src/responses.py", line 28, in <module>
    chatbot = get_chatbot_model(CHAT_MODEL)
  File "/data/chatGPT-discord-bot/src/responses.py", line 26, in get_chatbot_model
    return Chatbot(api_key=openai_api_key, engine=engine)
  File "/root/.pyenv/versions/discord-chatgpt/lib/python3.10/site-packages/revChatGPT/V3.py", line 69, in __init__
    if self.get_token_count("default") > self.max_tokens:
  File "/root/.pyenv/versions/discord-chatgpt/lib/python3.10/site-packages/revChatGPT/V3.py", line 103, in get_token_count
    raise NotImplementedError("Unsupported engine {self.engine}")
NotImplementedError: Unsupported engine {self.engine}

**Comment by berlin320** [comment]
same

**Comment by learningjohn** [comment]
same

**Comment by Zero6992** [comment]
fixed
