### ISSUE TITLE
Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

### ISSUE THREAD

**Issue by ryanshrott** [Zero6992/chatGPT-discord-bot#257]
Followed the instructions to install and getting this error. Is this a bug? How do I fix it?

2023-03-17 15:48:27 ERROR    discord.app_commands.tree Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\Ryan\anaconda3\envs\discordbot\lib\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\Ryan\PycharmProjects\chatGPT-discord-bot\src\bot.py", line 152, in chat
    await send_message(interaction, message)
  File "C:\Users\Ryan\PycharmProjects\chatGPT-discord-bot\src\bot.py", line 30, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ryan\anaconda3\envs\discordbot\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Ryan\anaconda3\envs\discordbot\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace        
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\Ryan\anaconda3\envs\discordbot\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by Zero6992** [comment]
see #230
