### ISSUE TITLE
Continuous issues when running prompt (cant even launch)

### ISSUE THREAD

**Issue by tjohnston1** [Zero6992/chatGPT-discord-bot#271]
Not sure what to do.
I have checked everything multiple times and it still will not run when the starting prompt is ran. 
It continues to say that it can find python and it is very clearly on my hard drive by the chatgpt bot.
**Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.**

I finally resolve that issue and instantly get hit with this message. 

C:\Python311\python.exe: can't open file 'C:\\Users\\trejo\\Downloads\\chatGPT-discord-bot-main\\main.py': [Errno 2] No such file or directory
PS C:\Users\trejo\Downloads\chatGPT-discord-bot-main>

What is wrong with this code and why am I having so many issues running this specifically?

**Comment by tjohnston1** [comment]
No longer know what to do at all....... I completely removed everything and started over.
Can't run pip3......wtf.....

PS C:\Users\trejo\Downloads\chatGPT-discord-bot-main\chatGPT-discord-bot-main> pip3 install -r requirements.txt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\pip3.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

**Comment by tjohnston1** [comment]
I was able to fix it after uninstalling the items required and running the same prompt on my computers cmd panel instead of VScode. After that everything worked flawless. When in doubt, take the code over to the computers direct panel!
