### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#275]
For some reason I am getting this while trying to run the bot

```
Traceback (most recent call last):
  File "/home/xxx/xxx/main.py", line 1, in <module>
    from src import bot
  File "/home/xxx/xxx/src/bot.py", line 3, in <module>
    import openai
```

I have the package installed, using python 3.10 and pip3

**Comment by frorayz** [comment]
> For some reason I am getting this while trying to run the bot
> 
> ```
> Traceback (most recent call last):
>   File "/home/xxx/xxx/main.py", line 1, in <module>
>     from src import bot
>   File "/home/xxx/xxx/src/bot.py", line 3, in <module>
>     import openai
> ```
> 
> I have the package installed, using python 3.10 and pip3

Never mind, was able to solve this by running it in virtualenv. Do not put two pip projects together lots of things break.
