### ISSUE TITLE
 Official GPT-4.0 model.

### ISSUE THREAD

**Issue by HusseinAhmed2** [Zero6992/chatGPT-discord-bot#278]
Command uses: Error: Something went wrong, please try again later!
--
Console error: 
Error while sending message: 404 Not Found {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
Traceback (most recent call last):
  File "/home/container/src/bot.py", line 35, in send_message
    response = f"{response}{await responses.official_handle_response(user_message)}"
  File "/home/container/src/responses.py", line 31, in official_handle_response
    return await sync_to_async(chatbot.ask)(message)
  File "/home/container/.local/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 223, in ask
    full_response: str = "".join(response)
  File "/home/container/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 182, in ask_stream
    raise error
revChatGPT.typing.APIConnectionError: 404 Not Found {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by Zero6992** [comment]
Do you have access to GPT-4?

**Comment by Zero6992** [comment]
#273
