### ISSUE TITLE
Error when running the bot

### ISSUE THREAD

**Issue by MegaWalls** [Zero6992/chatGPT-discord-bot#289]
This is the error that I got:

`Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\taisi\Downloads\chatGPT-discord-bot-1.1.3\chatGPT-discord-bot-1.1.3\main.py
[2023-03-24 20:16:21] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\taisi\Downloads\chatGPT-discord-bot-1.1.3\chatGPT-discord-bot-1.1.3\main.py", line 30, in <module>
    bot.run_discord_bot()
  File "C:\Users\taisi\Downloads\chatGPT-discord-bot-1.1.3\chatGPT-discord-bot-1.1.3\src\bot.py", line 408, in run_discord_bot
    client.run(TOKEN)
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Users\taisi\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead
`

**Comment by bilalbox** [comment]
@MegaWalls have you tried completing all of the [Critical Prerequisites](https://github.com/Zero6992/chatGPT-discord-bot#critical-prerequisites-to-install)? Perhaps your `.env` file is missing or misconfigured?

**Comment by MegaWalls** [comment]
All of them are completed. I filled in DISCORD_BOT_TOKEN, SESSION_TOKEN and OPENAI_API_KEY in the  .env.txt file.

**Comment by Zero6992** [comment]
`.env.txt` should be renmaed to `.env`

**Comment by MegaWalls** [comment]
Resolved

I had to name it somethingelse.env before deleting the part before .env
