### ISSUE TITLE
fata error when sending message

### ISSUE THREAD

**Issue by nekohacker591** [Zero6992/chatGPT-discord-bot#298]
[30;1m2023-03-27 18:02:21[0m [34;1mINFO    [0m [35msrc.bot[0m -> [31mreturn 0#4078[0m : /chat [test] in (chocola)
[2023-03-27 18:02:21] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\Downloads\chocola_bot\src\bot.py", line 32, in chat
    await client.send_message(interaction, message)
  File "C:\Users\micha\Downloads\chocola_bot\src\aclient.py", line 47, in send_message
    author = message.author.id
             ^^^^^^^^^^^^^^
AttributeError: 'Interaction' object has no attribute 'author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\micha\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by nekohacker591** [comment]
changes i did add new persona 
registered persona
change the os.getenv to real vals

**Comment by Zero6992** [comment]
check #230  for solution
