### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by shac1x** [Zero6992/chatGPT-discord-bot#309]
$ python3 main.py 

```py
Traceback (most recent call last):
  File "/home/renology/github-repo/chatGPT-discord-bot/main.py", line 33, in <module>
    check_version()
  File "/home/renology/github-repo/chatGPT-discord-bot/main.py", line 7, in check_version
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

My python ver is: 3.10.10

**Comment by NiceSapien** [comment]
I get the same error, but its slightly different, it says bard from bard stuff

**Comment by Zero6992** [comment]
https://stackoverflow.com/questions/59035724/python-error-no-module-named-pkg-resources

close this issue, as it is not related to this repo
