### ISSUE TITLE
Client error '403 Forbidden'

### ISSUE THREAD

**Issue by Rafee3r** [Zero6992/chatGPT-discord-bot#313]
v←[30;1m2023-03-30 20:59:08←[0m ←[31mERROR   ←[0m ←[35msrc.bot←[0m -> Error while sending starting prompt: Client error '403 Forbidden' for url 'https://bypass.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
←[31mTraceback (most recent call last):
  File "C:\Users\Alumno\Desktop\dou\ChatGPTDISCORD\chatGPT-discord-bot-main\src\bot.py", line 114, in send_start_prompt
    response = f"{response}{await responses.unofficial_handle_response(prompt)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alumno\Desktop\dou\ChatGPTDISCORD\chatGPT-discord-bot-main\src\responses.py", line 33, in unofficial_handle_response
    async for response in chatbot.ask(message):
  File "C:\Users\Alumno\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\Alumno\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1583, in stream
    yield response
  File "C:\Users\Alumno\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 825, in ask
    self.__check_response(response)
  File "C:\Users\Alumno\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 939, in __check_response
    response.raise_for_status()
  File "C:\Users\Alumno\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://bypass.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403←[0m

**Comment by Zero6992** [comment]
inactive issue
