### ISSUE TITLE
It works! but do I have to always keep my pc and pyhton on?

### ISSUE THREAD

**Issue by ImHack1993** [Zero6992/chatGPT-discord-bot#322]
The bot in the discord will just disconnect once my python is closed.
is there any way that I can make the bot always on so I can use it anywhere remotely?

**Comment by FuseFairy** [comment]
Can host on fly.io

**Comment by ImHack1993** [comment]
> Can host on fly.io

Tried for 3 hours but failed. fiald in writing a fly.toml file and make it work.
Do not have much programming experience😭

**Comment by namion** [comment]
Now is a great time to jump in and explore self hosting. Grab an old Toshiba Thinkcentre micro PC, install Proxmox and enjoy

**Comment by FuseFairy** [comment]
> > Can host on fly.io
> 
> Tried for 3 hours but failed. fiald in writing a fly.toml file and make it work. Do not have much programming experience😭

Follow the tutorial will be successful
https://www.youtube.com/watch?v=J7Fm7MdZn_E&t=15s

**Comment by ImHack1993** [comment]
> 

it works after another 3 hours!
but I face this after put the Discord/OpenAI/Bard Token as fly secret.
![image](https://user-images.githubusercontent.com/127242228/230104144-95b78d30-0c2c-4688-89a0-cd987f79f2d9.png)

```
2023-04-05T13:44:21.921 app[e78490da255383] lax [info] 2023-04-05 13:44:21 INFO src.bot -> Hack-GPT#7797 is now running!

2023-04-05T13:46:19.138 app[e78490da255383] lax [info] 2023-04-05 13:46:19 INFO src.bot -> Hack#3536 : /chat [are you online now] in (private)

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] [2023-04-05 13:46:19] [ERROR ] discord.app_commands.tree: Ignoring exception in command 'chat'

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] Traceback (most recent call last):

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 842, in _do_call

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] return await self._callback(interaction, **params) # type: ignore

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/DiscordBot/src/bot.py", line 32, in chat

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] await client.send_message(interaction, message)

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/DiscordBot/src/aclient.py", line 48, in send_message

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] author = message.author.id

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] AttributeError: 'Interaction' object has no attribute 'author'

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] The above exception was the direct cause of the following exception:

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] Traceback (most recent call last):

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] await command._invoke_with_namespace(interaction, namespace)

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] return await self._do_call(interaction, transformed_values)

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] raise CommandInvokeError(self, e) from e

2023-04-05T13:46:19.140 app[e78490da255383] lax [info] discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'
```

**Comment by ImHack1993** [comment]
eventually, it works!
