### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by HusseinAhmed2** [Zero6992/chatGPT-discord-bot#326]
official gpt version doesn't work 

Startup error:
2023-04-06 08:11:47 INFO     src.aclient -> Send system prompt with size 11
2023-04-06 08:11:47 ERROR    src.aclient -> Error while sending system prompt: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
Traceback (most recent call last):
  File "/home/container/src/aclient.py", line 134, in send_start_prompt
    response = f"{response}{await responses.official_handle_response(prompt, self)}"
  File "/home/container/src/responses.py", line 5, in official_handle_response
    return await sync_to_async(client.chatbot.ask)(message)
  File "/home/container/.local/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 335, in ask
    full_response: str = "".join(response)
  File "/home/container/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 201, in ask_stream
    raise t.APIConnectionError(
revChatGPT.typings.APIConnectionError: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by Zero6992** [comment]
#106
