### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by MaximRichter** [Zero6992/chatGPT-discord-bot#328]
Can't run bot. 
`
Traceback (most recent call last):
  File "D:\Useful stuff\chatGPT-discord-bot\main.py", line 1, in <module>
    from src import bot
  File "D:\Useful stuff\chatGPT-discord-bot\src\bot.py", line 5, in <module>
    from src.aclient import client
  File "D:\Useful stuff\chatGPT-discord-bot\src\aclient.py", line 150, in <module>
    client = aclient()
  File "D:\Useful stuff\chatGPT-discord-bot\src\aclient.py", line 39, in __init__
    self.chatbot = self.get_chatbot_model()
  File "D:\Useful stuff\chatGPT-discord-bot\src\aclient.py", line 44, in get_chatbot_model
    return AsyncChatbot(config={"email": self.openAI_email, "password": self.openAI_password, "access_token": self.chatgpt_access_token, "model": self.openAI_gpt_engine, "paid": self.chatgpt_paid})
  File "C:\Users\Maxim Richter\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 681, in __init__
    super().__init__(
  File "C:\Users\Maxim Richter\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Maxim Richter\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 130, in __init__
    cached_access_token = self.__get_cached_access_token(
  File "C:\Users\Maxim Richter\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Maxim Richter\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 249, in __get_cached_access_token
    s_access_token[1] += "=" * ((4 - len(s_access_token[1]) % 4) % 4)
IndexError: list index out of range
`

**Comment by MaximRichter** [comment]
Had to change model to "OFFICIAL" in config.
