### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by Mxfuuu** [Zero6992/chatGPT-discord-bot#333]
python main.py
2023-04-08 04:53:06 INFO     discord.client logging in using static token
2023-04-08 04:53:08 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 71e9c8a800cbf06efc30fb9aef481af2).
2023-04-08 04:53:10 INFO     src.aclient -> Send system prompt with size 11
2023-04-08 04:53:10 ERROR    src.aclient -> Error while sending system prompt: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
Traceback (most recent call last):
  File "C:\Users\Mxfuuu\Downloads\chatGPT-discord-bot-1.2.2\src\aclient.py", line 134, in send_start_prompt
    response = f"{response}{await responses.official_handle_response(prompt, self)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\Downloads\chatGPT-discord-bot-1.2.2\src\responses.py", line 5, in official_handle_response
    return await sync_to_async(client.chatbot.ask)(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V3.py", line 335, in ask
    full_response: str = "".join(response)
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Mxfuuu\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V3.py", line 201, in ask_stream
    raise t.APIConnectionError(
revChatGPT.typings.APIConnectionError: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

Please check if there is a problem with your network connection
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

**Comment by Zero6992** [comment]
#106
