### ISSUE TITLE
bot running, but I have this issue here... what do I do?

### ISSUE THREAD

**Issue by r4z3nn** [Zero6992/chatGPT-discord-bot#338]
2023-04-09 16:13:55 INFO     discord.client logging in using static token
2023-04-09 16:13:56 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 21842810f2f2cab9ddb0976114700404).
2023-04-09 16:13:58 INFO     src.aclient -> Send system prompt with size 11
2023-04-09 16:13:58 ERROR    src.aclient -> Error while sending system prompt: Illegal header value b'Bearer '
Traceback (most recent call last):
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 121, in _send_request_headers
    event = h11.Request(
            ^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\h11\_events.py", line 96, in __init__
    self, "headers", normalize_and_validate(headers, _parsed=_parsed)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\h11\_headers.py", line 164, in normalize_and_validate
    validate(_field_value_re, value, "Illegal header value {!r}", value)
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\h11\_util.py", line 91, in validate
    raise LocalProtocolError(msg)
h11._util.LocalProtocolError: Illegal header value b'Bearer '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 80, in handle_async_request
    await self._send_request_headers(**kwargs)
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\http11.py", line 120, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ninoa\Downloads\chatGPT-discord-bot-main\src\aclient.py", line 136, in send_start_prompt
    response = f"{response}{await responses.unofficial_handle_response(prompt, self)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\Downloads\chatGPT-discord-bot-main\src\responses.py", line 8, in unofficial_handle_response
    async for response in client.chatbot.ask(message):
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 742, in ask
    async with self.session.stream(
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1576, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ninoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'Bearer '

**Comment by RayDog1995** [comment]
Same issue, is it the API key incorrect?

**Comment by Zero6992** [comment]
The correct OpenAI API key is required

**Comment by RayDog1995** [comment]
Why is this link in the instructions: https://beta.openai.com/account/api-keys. I got the api from there, made sure I had the $18 credits. What is the correct link to get the right api?
