### ISSUE TITLE
revChatGPT.typings.NotAllowRunning: Not available Python version: 3.8.10

### ISSUE THREAD

**Issue by sirouk** [Zero6992/chatGPT-discord-bot#344]
All requirements are installed and updated.

I'm running into this issue even after removing the revChatGPT module and installing it again.

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src import bot
  File "/home/someuser/swa-chatgpt-discord/chatGPT-discord-bot/src/bot.py", line 5, in <module>
    from src.aclient import client
  File "/home/someuser/swa-chatgpt-discord/chatGPT-discord-bot/src/aclient.py", line 8, in <module>
    from revChatGPT.V3 import Chatbot
  File "/home/someuser/.local/lib/python3.8/site-packages/revChatGPT/__init__.py", line 23, in <module>
    raise error
revChatGPT.typings.NotAllowRunning: Not available Python version: 3.8.10
```

**Comment by sirouk** [comment]
Ok, thanks!
