### ISSUE TITLE
No Idea

### ISSUE THREAD

**Issue by BraydenMee** [Zero6992/chatGPT-discord-bot#353]
C:\Users\titan\Downloads\chatGPT-discord-bot-1.3.2\chatGPT-discord-bot-1.3.2>python main.py
Traceback (most recent call last):
  File "C:\Users\titan\Downloads\chatGPT-discord-bot-1.3.2\chatGPT-discord-bot-1.3.2\main.py", line 1, in <module>
    from src import bot
  File "C:\Users\titan\Downloads\chatGPT-discord-bot-1.3.2\chatGPT-discord-bot-1.3.2\src\bot.py", line 5, in <module>
    from src.aclient import client
  File "C:\Users\titan\Downloads\chatGPT-discord-bot-1.3.2\chatGPT-discord-bot-1.3.2\src\aclient.py", line 6, in <module>
    from discord import app_commands
  File "C:\Users\titan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\__init__.py", line 12, in <module>
    from .commands import *
  File "C:\Users\titan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 50, in <module>
    from ..enums import AppCommandOptionType, AppCommandType, ChannelType, Locale
ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums' (C:\Users\titan\AppData\Roaming\Python\Python310\site-packages\discord\enums.py)

**Comment by Zero6992** [comment]
Please provide more detailed information about your environment

And check #40

**Comment by Zero6992** [comment]
Lack of activity
