### ISSUE TITLE
Bing is Broken

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#360]
Getting this when trying to switch. I have my cookies.json set
```2023-04-22 14:40:42 ERROR    src.bot -> Error while switching to the Bing model: Chatbot.__init__() got an unexpected keyword argument 'cookiePath'
Traceback (most recent call last):
  File "/home/xxx/xxx/src/bot.py", line 113, in chat_model
    client.chatbot = client.get_chatbot_model()
  File "/home/xxx/xxx/src/aclient.py", line 51, in get_chatbot_model
    return EdgeChatbot(cookiePath='./cookies.json')
TypeError: Chatbot.__init__() got an unexpected keyword argument 'cookiePath'
```

**Comment by Zero6992** [comment]
fixed!

**Comment by frorayz** [comment]
@Zero6992 Another error now. 
```2023-04-22 19:17:39 ERROR    src.aclient -> Error while sending message: 'text'
Traceback (most recent call last):
  File "/xx/xx/xx/src/aclient.py", line 73, in send_message
    response = f"{response}{await responses.bing_handle_response(user_message, self)}"
  File "/xx/xx/xx/src/responses.py", line 21, in bing_handle_response
    return responseMessage[1]["item"]["messages"][1]["text"]
KeyError: 'text'```
