### ISSUE TITLE
Blocked API RateLimit

### ISSUE THREAD

**Issue by Hide-in-base** [Zero6992/chatGPT-discord-bot#368]
Can you help me fix this please

```
Traceback (most recent call last):
  File "/home/container/main.py", line 30, in <module>
    bot.run_discord_bot()
  File "/home/container/src/bot.py", line 289, in run_discord_bot
    client.run(TOKEN)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/home/container/.local/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/container/.local/lib/python3.10/site-packages/discord/http.py", line 680, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.
```

**Comment by Hide-in-base** [comment]
Just tell me what should I put in my code to make ratelimit please:)

**Comment by Zero6992** [comment]
Please provide your environment
