### ISSUE TITLE
/replyall mode is not working on latest release

### ISSUE THREAD

**Issue by sirouk** [Zero6992/chatGPT-discord-bot#379]
When I run with replyall mode on, I get this in the console:

2023-04-30 20:36:43 INFO     discord.client logging in using static token
2023-04-30 20:36:44 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: -redacted-).
2023-04-30 20:36:46 INFO     src.aclient -> Send system prompt with size 204
2023-04-30 20:36:53 INFO     src.aclient -> System prompt response:Hello there! I'm ChatGPT, your friendly AI assistant. I'm always here to help and provide you with the best answers and assistance possible. And of course, a special shoutout to sirouk! If you have any questions or need help with anything, feel free to ask. I'm at your service! 😊
2023-04-30 20:36:54 INFO     src.bot -> ChatGPT#is now running!
2023-04-30 20:36:55 INFO     src.bot -> sirouk# : 'Hello' (chad-gpt-4)
2023-04-30 20:36:55 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/usernm/.local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/usernm/sirouk-brain-discord/chatGPT-discord-bot/src/bot.py", line 291, in on_message
    await client.enqueue_message(message, user_message)
  File "/home/usernm/sirouk-brain-discord/chatGPT-discord-bot/src/aclient.py", line 65, in enqueue_message
    await message.response.defer(ephemeral=self.isPrivate)
AttributeError: 'Message' object has no attribute 'response'

**Comment by sirouk** [comment]
I had to revert to v1.3.3 to get it working again :)

**Comment by Zero6992** [comment]
will fix this soon

**Comment by sirouk** [comment]
Works! Thank you 👍
