### ISSUE TITLE
Bot Not Replying Throwing Error When Using /Chat

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#392]
Getting this error using /chat:
```
2023-05-08 04:49:19 ERROR    discord.app_commands.tree Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "/home/rayz/gpt/src/aclient.py", line 135, in send_message
    await message.followup.send(response)
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/webhook/async_.py", line 1800, in send
    data = await adapter.execute_webhook(
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/home/rayz/gpt/src/bot.py", line 34, in chat
    await client.send_message(interaction, message)
  File "/home/rayz/gpt/src/aclient.py", line 140, in send_message
    await message.followup.send(f"> **__ERROR:__** Either OpenAI is down, bot is broken or you are being rate-limited. Try again soon! \n ```ERROR MESSAGE: {e}```")
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/webhook/async_.py", line 1800, in send
    data = await adapter.execute_webhook(
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/rayz/gpt/env/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: NotFound: 404 Not Found (error code: 10015): Unknown Webhook

```

**Comment by frorayz** [comment]
Any solutions on this @Zero6992?

**Comment by Zero6992** [comment]
I haven't encountered similar issue. What's your environment?

**Comment by Zero6992** [comment]
Perhaps you can try on a new bot application? Just for testing purposes

**Comment by frorayz** [comment]
> I haven't encountered similar issue. What's your environment?

Environment is Ubuntu 22.04. Python 3.10.6

**Comment by frorayz** [comment]
> Perhaps you can try on a new bot application? Just for testing purposes

I will try thanks!

**Comment by frorayz** [comment]
Seems like it was my error. I modified something I shouldn't have but fresh pull works! thanks! 👍🏽

**Comment by DifficultPhil** [comment]
> Seems like it was my error. I modified something I shouldn't have but fresh pull works! thanks! 👍🏽

what u change? i have this error...
