### ISSUE TITLE
    author = message.author.id AttributeError: 'Interaction' object has no attribute 'author'

### ISSUE THREAD

**Issue by TuanLeDevelopment** [Zero6992/chatGPT-discord-bot#399]
Traceback (most recent call last):
  File "/root/Bots/Gpt/src/aclient.py", line 58, in process_messages
    await self.send_message(message, user_message)
  File "/root/Bots/Gpt/src/aclient.py", line 72, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'

**Comment by DinuNuggets** [comment]
#386 Check your .env file
