### ISSUE TITLE
Clear data feature 

### ISSUE THREAD

**Issue by Murat1Ahmet** [Zero6992/chatGPT-discord-bot#401]
Hello, I hope you add feature to allow users delete there data from the logs, like /clear_data to delete there conversation history from the bot

**Comment by Murat1Ahmet** [comment]
Also i have question pls if i remove logs from code can i run the bot without message content require from developer portal ?

**Comment by Zero6992** [comment]
If you don't want to log, you can set the `LOGGING  to `False `in the `.env` file. And if you need to reset the chat, simply use the `/reset` command

**Comment by Zero6992** [comment]
And no, the bot does need permission to read message content with or without logging

**Comment by Murat1Ahmet** [comment]
> And no, the bot does need permission to read message content with or without logging

when its on my bot work normally, when i turn it off i get this error

2023-05-17 14:42:41 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/container/main.py", line 30, in <module>
    bot.run_discord_bot()
  File "/home/container/src/bot.py", line 113, in run_discord_bot
    client.run(TOKEN)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by Zero6992** [comment]
That's what I mean, you do need `MESSAGE CONTENT INTENT` ON

**Comment by Zero6992** [comment]
Follow the `README`

**Comment by Zero6992** [comment]
Mirtris#9999 in discord
