### ISSUE TITLE
error when run bot (help me :(()

### ISSUE THREAD

**Issue by Quocdesigner** [Zero6992/chatGPT-discord-bot#407]
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\main.py", line 1, in <module>
    from src import bot
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\src\bot.py", line 6, in <module>
    from src.aclient import client
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\src\aclient.py", line 194, in <module>
    client = aclient()
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\src\aclient.py", line 43, in __init__
    chrome_version = int(os.getenv("chrome_version")) if bard_enable_auto_login == 'True' or bing_enable_auto_login == 'True' else None
ValueError: invalid literal for int() with base 10: '113.0.5672.127'

**Comment by Zero6992** [comment]
Just put `113` in `chrome_version`

**Comment by Quocdesigner** [comment]
And then it displays this error message:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\main.py", line 29, in <module>
    check_version()
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_4\chatGPT-discord-bot-main\main.py", line 20, in check_version
    installed = pkg_resources.get_distribution(package_name)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 480, in get_distribution
    raise TypeError("Expected string, Requirement, or Distribution", dist)
TypeError: ('Expected string, Requirement, or Distribution', ['discord.py', '2.2.2'])

see image: https://i.imgur.com/eQiNEpb.png

**Comment by Quocdesigner** [comment]
help me pls  :((

**Comment by Quocdesigner** [comment]
> pull the latest code could fix it

Where can I download the latest code snippet

**Comment by Quocdesigner** [comment]
> `git clone` or download the zip file from the latest releases

with new error:
2023-05-24 14:59:19 ERROR    src.aclient -> Error while sending system prompt: InternalError: Unhandled Dependency Failure: DeepLeo
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_5\chatGPT-discord-bot-main\src\aclient.py", line 182, in send_start_prompt
    response = f"{response}{await responses.bing_handle_response(prompt, self)}"
  File "C:\Users\ASUS\Desktop\chatGPT-discord-bot-main_5\chatGPT-discord-bot-main\src\responses.py", line 18, in bing_handle_response
    async for response in client.chatbot.ask_stream(message):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 674, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 549, in ask_stream
    raise Exception(
Exception: InternalError: Unhandled Dependency Failure: DeepLeo

image: https://i.imgur.com/rFVtqFw.png

**Comment by Quocdesigner** [comment]
im [still waiting](https://tr-ex.me/d%E1%BB%8Bch/ti%E1%BA%BFng+anh-ti%E1%BA%BFng+vi%E1%BB%87t/is+still+waiting)

**Comment by Quocdesigner** [comment]
im still waiting

**Comment by Zero6992** [comment]
This is an error from Bing's end. Can you tell me how to reproduce this error?

**Comment by Zero6992** [comment]
And does it happens all the time?

**Comment by badong3521** [comment]
I also encountered the same error as you
