### ISSUE TITLE
I'm having this problem that says I exceeded the daily command limit, but it's been a few days... does anyone know what it would be?

### ISSUE THREAD

**Issue by LMrAllan** [Zero6992/chatGPT-discord-bot#415]
[2023-05-31 07:37:44] [INFO    ] discord.client: logging in using static token
[2023-05-31 07:37:46] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ...).
[30;1m2023-05-31 07:37:48[0m [34;1mINFO    [0m [35msrc.aclient[0m -> Send system prompt with size 11
[30;1m2023-05-31 07:37:49[0m [34;1mINFO    [0m [35msrc.aclient[0m -> System prompt response:General Kenobi!
[2023-05-31 07:37:49] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\alan1\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\alan1\OneDrive\�rea de Trabalho\chatGPT-discord-bot-main\src\bot.py", line 16, in on_ready
    await client.tree.sync()
  File "C:\Users\alan1\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\tree.py", line 1067, in sync
    data = await self._http.bulk_upsert_global_commands(self.client.application_id, payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alan1\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200)

**Comment by TaijiMonster** [comment]
Same issue here....

**Comment by LMrAllan** [comment]
apparently it was really just a discord restriction, because 1 day passed and it worked

**Comment by TaijiMonster** [comment]
its working now
