### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by lmc87lmc** [Zero6992/chatGPT-discord-bot#428]
I have tried refreshing the cookie, reinstalling the bot but I still have this issue with bard
![Screenshot_20230620-083449](https://github.com/Zero6992/chatGPT-discord-bot/assets/90536980/0851a81e-8c6e-48d0-b35d-dca862d3dd25)

**Comment by lmc87lmc** [comment]
Also got this when updating, don't know if relevant Traceback (most recent call last):
  File "c:\Users\maste\Downloads\chatGPT-discord-bot-1.5.1\chatGPT-discord-bot-1.5.1\main.py", line 1, in <module> 
    from src import bot
  File "c:\Users\maste\Downloads\chatGPT-discord-bot-1.5.1\chatGPT-discord-bot-1.5.1\src\bot.py", line 6, in <module>
    from src.aclient import client
  File "c:\Users\maste\Downloads\chatGPT-discord-bot-1.5.1\chatGPT-discord-bot-1.5.1\src\aclient.py", line 11, in <module>
    from EdgeGPT import Chatbot as EdgeChatbot
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (C:\Users\maste\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\__init__.py)
PS C:\Users\maste\Downloads\chatGPT-discord-bot-1.5.1\chatGPT-discord-bot-1.5.1>
