### ISSUE TITLE
Error whilst attempting to switch persona; "ERROR: Something went wrong, please try again later! 😿"

### ISSUE THREAD

**Issue by yo1nkers** [Zero6992/chatGPT-discord-bot#430]
2023-06-29 22:44:56 chatgpt-discord-bot  | 2023-06-29 13:14:56 INFO     src.log -> yoinkers. : '/switchpersona [sda]' (announce)
2023-06-29 22:44:56 chatgpt-discord-bot  | 2023-06-29 13:14:56 ERROR    src.log -> Error while switching persona: aclient.get_chatbot_model() got an unexpected keyword argument 'prompt'
2023-06-29 22:44:56 chatgpt-discord-bot  | Traceback (most recent call last):
2023-06-29 22:44:56 chatgpt-discord-bot  |   File "/DiscordBot/src/bot.py", line 305, in switchpersona
2023-06-29 22:44:56 chatgpt-discord-bot  |     await responses.switch_persona(persona, client)
2023-06-29 22:44:56 chatgpt-discord-bot  |   File "/DiscordBot/src/responses.py", line 41, in switch_persona
2023-06-29 22:44:56 chatgpt-discord-bot  |     client.chatbot = client.get_chatbot_model(prompt=personas.PERSONAS.get(persona))
2023-06-29 22:44:56 chatgpt-discord-bot  | TypeError: aclient.get_chatbot_model() got an unexpected keyword argument 'prompt'

**Comment by Zero6992** [comment]
fixed
