### ISSUE TITLE
main error 

### ISSUE THREAD

**Issue by Y4nN0xX** [Zero6992/chatGPT-discord-bot#440]
Hi, any fix for that please 
tyty
```
Traceback (most recent call last):
  File "/root/ia/main.py", line 30, in <module>
    check_version()
  File "/root/ia/main.py", line 20, in check_version
    package_name, package_version = package.split('==')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Mr-Tyke** [comment]
Did you delete or alter the requirements.txt?

**Comment by Y4nN0xX** [comment]
> Did you delete or alter the requirements.txt?

fixed brain issue , i renamed main file chatGPT-discord-bot to ia ...
