### ISSUE TITLE
Bard /chat issue after abit of using /chat

### ISSUE THREAD

**Issue by Murat1Na** [Zero6992/chatGPT-discord-bot#452]
when i use /chat it work but after like 10 minutes , when i try to use it, the bot keep thinking and doesnt reply.

Task exception was never retrieved
future: <Task finished name='Task-892' coro=<aclient.process_messages() done, defined at /home/container/src/aclient.py:85> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "/home/container/src/aclient.py", line 89, in process_messages
    async with self.current_channel.typing():
  File "/home/container/.local/lib/python3.9/site-packages/discord/context_managers.py", line 82, in __aenter__
    await channel._state.http.send_typing(channel.id)
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

**Comment by Murat1Na** [comment]
also /reset doesnt work

**Comment by Zero6992** [comment]
discord permission issue
https://stackoverflow.com/questions/70351522/403-forbidden-error-code-50001-missing-access-discord-py
