### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by NekuSakr** [Zero6992/chatGPT-discord-bot#453]
C:\Users\lizhe>C:\Users\lizhe\chatGPT-discord-bot-main\main.py
Traceback (most recent call last):
  File "C:\Users\lizhe\chatGPT-discord-bot-main\main.py", line 4, in <module>
    from src import bot
  File "C:\Users\lizhe\chatGPT-discord-bot-main\src\bot.py", line 7, in <module>
    from src.aclient import client
  File "C:\Users\lizhe\chatGPT-discord-bot-main\src\aclient.py", line 7, in <module>
    from src import responses
  File "C:\Users\lizhe\chatGPT-discord-bot-main\src\responses.py", line 4, in <module>
    from EdgeGPT.EdgeGPT import ConversationStyle
ModuleNotFoundError: No module named 'EdgeGPT'

Why does it say the edgeGPT module?

**Comment by pjpmosteiro** [comment]
Tried "pip3 install -r requirements.txt" ?

**Comment by NekuSakr** [comment]
> Tried "pip3 install -r requirements.txt" ?

Ye I already done all the preparation steps but it keeps telling me this :(

**Comment by Zero6992** [comment]
Please delete all files and then try to repeat all the steps again

**Comment by Zero6992** [comment]
If the error goes on, please provide your environment, OS and Python version

**Comment by Vixxel** [comment]
It has been a few weeks now, are there any updates regarding the issue you were going through?
