### ISSUE TITLE
get error and bot doesn't work.

### ISSUE THREAD

**Issue by faldoto** [Zero6992/chatGPT-discord-bot#454]
discribed errors 

Traceback (most recent call last):
  File "C:\Users\USERNAME\chatGPT-discord-bot-main\chatGPT-discord-bot-main\main.py", line 4, in <module>
    from src import bot
  File "C:\Users\USERNAME\chatGPT-discord-bot-main\chatGPT-discord-bot-main\src\bot.py", line 7, in <module>
    from src.aclient import client
  File "C:\Users\USERNAME\chatGPT-discord-bot-main\chatGPT-discord-bot-main\src\aclient.py", line 13, in <module>
    from discord import app_commands
  File "C:\Python311\Lib\site-packages\discord\app_commands\__init__.py", line 12, in <module>
    from .commands import *
  File "C:\Python311\Lib\site-packages\discord\app_commands\commands.py", line 51, in <module>
    from ..enums import  AppCommandOptionType, AppCommandType, Locale
ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums' (C:\Users\USERNAME\AppData\Roaming\Python\Python311\site-packages\discord\enums.py)

please let me know the solution.

**Comment by Zero6992** [comment]
It might be an environmental issue.

check #40
