### ISSUE TITLE
Problems Running the bot

### ISSUE THREAD

**Issue by skygamer125** [Zero6992/chatGPT-discord-bot#46]
I've been able to run the bot in my windows system naturally. Using the user-agent that my web browser uses.

However as I tried to upload the bot to a host, the bot simply refuses to work, and as far as I've analysed the problem is related to the User-Agent.

So I wonder how I'd be able to upload this bot to a hosting service... and still be able to make it run

Running on windows:
![image](https://user-images.githubusercontent.com/41944315/206991544-b080c3b5-746d-44e1-932a-f929b31ed6ae.png)

Running on Hosting service with the exact same files:
![image](https://user-images.githubusercontent.com/41944315/206991652-e70e07ec-e345-44e9-828a-cc4cc616da7f.png)

I'm quite new to User-agent related stuff, so I don't really know what I can do about this.

**Comment by khlsvr** [comment]
I have the same problem.

What I've done: I found my bot not being able to authenticate this morning and noticed that I needed to git pull as I had old config.json and requirements.txt had newer versions for things. I input values to the new config.json requiring the user agent field aswell. With firefox's devtools network tab I didn't see any user agent there so I checked from qutebrowsers devtools and just picked one that looked like the same one that was picked in the setup screenshot here on github. After trying to run the bot I get exact same error as you about the wrong response code.

**Comment by Longyichen** [comment]
Me too, it seems that chatgpt wepage refreash its token frequently.

**Comment by skygamer125** [comment]
It is working for me. when I use it on windows. when I upload to the hosting service it just wont work.

I tried creating my own user agent like chatGPT had recommended me:
![image](https://user-images.githubusercontent.com/41944315/206994460-7e49b7a2-0cfa-4dfa-a5a0-92162f22d8a6.png)

And then used it on my browser to generate the new session_token + cf_clearance
![image](https://user-images.githubusercontent.com/41944315/206994624-cbdca6b3-cf18-49c4-be5a-acc0c7f6b0ef.png)

and then I tried running it on windows, and it worked. it worked perfectly.

However again, after uploading it to the hosting service, it just didn't wanna work at all.
I even tried downloading what was in the server and running it locally, which worked too. So something is either wrong with my hosting service or idk..

**Comment by Longyichen** [comment]
@skygamer125 you are right 

I try on my mac and it works!
Maybe openai ban the ip of server?
Can you try another server?

**Comment by skygamer125** [comment]
I'm trying it rn

**Comment by skygamer125** [comment]
Tried on 2 different hosts and it didn't work

**Comment by aW3ikun** [comment]
Me too. I encounter the same error in the Codespaces of GitHub. And I have tried 2 American server IPs, which don't work.
```bash
@aW3ikun ➜ /workspaces/chatGPT-discord-bot (fix-errors ✗) $ python3 main.py 
Traceback (most recent call last):
  File "/workspaces/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/workspaces/chatGPT-discord-bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/workspaces/chatGPT-discord-bot/src/responses.py", line 34, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/home/codespace/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/home/codespace/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```

**Comment by Zero6992** [comment]
It should be related to Cloudfare refer to [#261](https://github.com/acheong08/ChatGPT/issues/261)

**Comment by Zero6992** [comment]
The `cf_clearance` cookie is tied to a combination of your IP address and `user-agent`, and is currently valid for 2 hour

**Comment by Longyichen** [comment]
@Zero6992 
The author seems to have fixed this bug in this branch：
https://github.com/acheong08/ChatGPT/tree/cloudflare
In order to solve the cloudfare problem, we need to modify the configuration file
https://github.com/acheong08/ChatGPT/wiki/Setup
But it seems that this update is not available from pip at the moment. Please change the readme if this project is updated, thanks!

**Comment by skygamer125** [comment]
I failed to comprehend what this exactly meant. A solution is possible in the future or the bot will just never work outside of my current IP? :V and I'll have to refresh it manually every 2 hrs?

**Comment by Zero6992** [comment]
> @Zero6992 The author seems to have fixed this bug in this branch： https://github.com/acheong08/ChatGPT/tree/cloudflare In order to solve the cloudfare problem, we need to modify the configuration file https://github.com/acheong08/ChatGPT/wiki/Setup But it seems that this update is not available from pip at the moment. Please change the readme if this project is updated, thanks!

Updated

The `cf_clearance` token is automatically fetched now, but cannot run in docker

**Comment by Zero6992** [comment]
> I failed to comprehend what this exactly meant. A solution is possible in the future or the bot will just never work outside of my current IP? :V and I'll have to refresh it manually every 2 hrs?

The solution is already WIP

**Comment by skygamer125** [comment]
Got it! I'm sad I cant be of use here. Good luck!

**Comment by Zero6992** [comment]
> i could not get it running by any means since cloudflare with docker

Changing the revChatGPT version in `requirements.txt` to `0.0.38.8` will allow you to run it in Docker

 but you'll need to manually renew cf_clearance every two hours, we are working on this

**Comment by ziipzaaapM16A4** [comment]
I already tried this. Result:
```
Traceback (most recent call last):
  File "/DiscordBot/main.py", line 1, in <module>
    from src import bot
  File "/DiscordBot/src/bot.py", line 3, in <module>
    from src import responses
  File "/DiscordBot/src/responses.py", line 34, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```
```
"user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by namion** [comment]
The bot is completely broken for me now:

_Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS W:\AI Art\ChatGPT\chatGPT-discord-bot> python main.py
Traceback (most recent call last):
  File "W:\AI Art\ChatGPT\chatGPT-discord-bot\main.py", line 1, in <module>
    from src import bot
  File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\bot.py", line 3, in <module>
    from src import responses
  File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\responses.py", line 1, in <module>
    from revChatGPT.revChatGPT import AsyncChatbot as Chatbot
ImportError: cannot import name 'AsyncChatbot' from 'revChatGPT.revChatGPT' (C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py)
PS W:\AI Art\ChatGPT\chatGPT-discord-bot>_

**Comment by Zero6992** [comment]
> 



> I already tried this. i filled all the values of the config and i run the docker container on my pc locally which means there is no other ip adress used than the one the cf_clearence has been created.
> 
> Result:
> 
> ```
> Traceback (most recent call last):
>   File "/DiscordBot/main.py", line 1, in <module>
>     from src import bot
>   File "/DiscordBot/src/bot.py", line 3, in <module>
>     from src import responses
>   File "/DiscordBot/src/responses.py", line 34, in <module>
>     chatbot = Chatbot(config, conversation_id=None)
>   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
>     self.refresh_session()
>   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
>     raise Exception("Wrong response code")
> Exception: Wrong response code
> ```
> 
> ```
> "user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
> ```

Have you tried to reproduce the session token?

**Comment by skygamer125** [comment]
CHATGPT IS CURRENTLY OVERLOADED:
https://chat.openai.com/auth/login
![image](https://user-images.githubusercontent.com/41944315/207119254-4f6e4542-b41b-4247-914a-e37f860e8d64.png)

**Comment by Zero6992** [comment]
> The bot is completely broken for me now:
> 
> _Windows PowerShell Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6
> 
> PS W:\AI Art\ChatGPT\chatGPT-discord-bot> python main.py Traceback (most recent call last): File "W:\AI Art\ChatGPT\chatGPT-discord-bot\main.py", line 1, in from src import bot File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\bot.py", line 3, in from src import responses File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\responses.py", line 1, in from revChatGPT.revChatGPT import AsyncChatbot as Chatbot ImportError: cannot import name 'AsyncChatbot' from 'revChatGPT.revChatGPT' (C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py) PS W:\AI Art\ChatGPT\chatGPT-discord-bot>_

What environment are you running, and what version of revChatGPT are you using?

**Comment by Zero6992** [comment]
> CHATGPT is currently overloaded: https://chat.openai.com/auth/login ![image](https://user-images.githubusercontent.com/41944315/207119254-4f6e4542-b41b-4247-914a-e37f860e8d64.png)

yeah, it's a bit annoying

It's been giving errors frequently lately and I hope it's just temporary

**Comment by skygamer125** [comment]
Same, Just saying, cause people might blame the bot for it instead of seeing what's actually happening, and it also makes it more difficult for us to try to use it in the ways we desire .3. its a pain

**Comment by namion** [comment]
> > The bot is completely broken for me now:
> > _Windows PowerShell Copyright (C) Microsoft Corporation. All rights reserved.
> > Try the new cross-platform PowerShell https://aka.ms/pscore6
> > PS W:\AI Art\ChatGPT\chatGPT-discord-bot> python main.py Traceback (most recent call last): File "W:\AI Art\ChatGPT\chatGPT-discord-bot\main.py", line 1, in from src import bot File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\bot.py", line 3, in from src import responses File "W:\AI Art\ChatGPT\chatGPT-discord-bot\src\responses.py", line 1, in from revChatGPT.revChatGPT import AsyncChatbot as Chatbot ImportError: cannot import name 'AsyncChatbot' from 'revChatGPT.revChatGPT' (C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py) PS W:\AI Art\ChatGPT\chatGPT-discord-bot>_
> 
> What environment are you running, and what version of revChatGPT are you using?

Whoops! I did a git pull but didn't rerun the requirements. I updated the requirements and it is working now. Sorry, I'm a bit of a noob with all of this github and python stuff. Thank you for all of your work on this. 😀

**Comment by ziipzaaapM16A4** [comment]
> > 
> 
> > I already tried this. i filled all the values of the config and i run the docker container on my pc locally which means there is no other ip adress used than the one the cf_clearence has been created.
> > Result:
> > ```
> > Traceback (most recent call last):
> >   File "/DiscordBot/main.py", line 1, in <module>
> >     from src import bot
> >   File "/DiscordBot/src/bot.py", line 3, in <module>
> >     from src import responses
> >   File "/DiscordBot/src/responses.py", line 34, in <module>
> >     chatbot = Chatbot(config, conversation_id=None)
> >   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
> >     self.refresh_session()
> >   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
> >     raise Exception("Wrong response code")
> > Exception: Wrong response code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > "user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
> > ```
> 
> Have you tried to reproduce the session token?

yes

**Comment by Zero6992** [comment]
There is an updated version

**Comment by skygamer125** [comment]
So there's no way to run it independently? and host it in discord's bot hosting service then? :V only through docker?

**Comment by Zero6992** [comment]
> So there's no way to run it independently? and host it in discord's bot hosting service then? :V only through docker?

To successfully pass the cloudflare verification, you need to have a window manager in the location where you want to run it

Using docker can make this process much easier for you

**Comment by skygamer125** [comment]
Got it, I wonder what hosting services for discord bots would support that... hmm
