### ISSUE TITLE
bing doesnt work

### ISSUE THREAD

**Issue by pqr29** [Zero6992/chatGPT-discord-bot#470]
2023-09-23 16:51:57 INFO     src.log -> tzr78 : /chat [holii] in (general)
2023-09-23 16:52:00 ERROR    src.log -> Error occurred: CaptchaChallenge: User needs to solve CAPTCHA to continue.
2023-09-23 16:52:00 ERROR    src.log -> Error while sending : CaptchaChallenge: User needs to solve CAPTCHA to continue.
Bing is fail to continue the conversation, this conversation will automatically reset.
Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\test\chatGPT-discord-bot\src\responses.py", line 21, in bing_handle_response
    response = await client.chatbot.ask(prompt = message,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\chathub.py", line 207, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\test\chatGPT-discord-bot\src\aclient.py", line 125, in send_message
    response = f"{response}{await responses.bing_handle_response(user_message, self)}"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\Downloads\test\chatGPT-discord-bot\src\responses.py", line 28, in bing_handle_response
    raise Exception(f'{e}\nBing is fail to continue the conversation, this conversation will automatically reset.')
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Bing is fail to continue the conversation, this conversation will automatically reset.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BA20FFE950>

**Comment by Zero6992** [comment]
Refresh your cookies
