### ISSUE TITLE
Error with autologin Bard

### ISSUE THREAD

**Issue by Myntyy** [Zero6992/chatGPT-discord-bot#480]
Hi, i've this error and tried to solve it without success. Any ideas?

Initializing auto login for Google Bard ...
Visiting https://bard.google.com/ ...
Finding sign-in button ...
Traceback (most recent call last):
  File "/home/meteion/chatGPT-discord-bot/main.py", line 4, in <module>
    from src import bot
  File "/home/meteion/chatGPT-discord-bot/src/bot.py", line 7, in <module>
    from src.aclient import client
  File "/home/meteion/chatGPT-discord-bot/src/aclient.py", line 163, in <module>
    client = aclient()
             ^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/src/aclient.py", line 48, in __init__
    self.bard_session_id = GoogleBardAutoLogin(google_account, google_password, chrome_version).get_cookie()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/auto_login/AutoLogin.py", line 81, in get_cookie
    cookie_list = self.get_cookie_list()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/auto_login/AutoLogin.py", line 67, in get_cookie_list
    password_input = self.find_password_input()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/auto_login/AutoLogin.py", line 56, in find_password_input
    self.find_account_input().send_keys(self.google_account + Keys.RETURN)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/auto_login/AutoLogin.py", line 49, in find_account_input
    self.find_sign_in_button().click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteion/chatGPT-discord-bot/auto_login/AutoLogin.py", line 46, in find_sign_in_button
    raise NoSuchElementException('No element has inner text value - "Sign in"')
selenium.common.exceptions.NoSuchElementException: Message: No element has inner text value - "Sign in"

I'm on Debian 12
Python 3.11.2

Thanks

**Comment by Zero6992** [comment]
Updated
