### ISSUE TITLE
[Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by DasX** [Zero6992/chatGPT-discord-bot#494]
When i run the Bot on my Server either directly or through docker it both ends up there. 

im using unoffical with either gpt 3.5 turbo or gpt 4

[Errno -5] No address associated with hostname when using /chat

Something Went Wrong: Connection error. when using /draw

**Comment by kennhardy** [comment]
I'm getting the same running mine in a docker-compose trying to use the unofficial gpt.
```Traceback (most recent call last):
  File "/DiscordBot/src/aclient.py", line 115, in send_message
    response = f"{response}{await responses.unofficial_handle_response(user_message, self)}"
  File "/DiscordBot/src/responses.py", line 11, in unofficial_handle_response
    async for response in client.chatbot.ask(message):
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1331, in ask
    async for msg in self.post_messages(
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1282, in post_messages
    async for msg in self.__send_request(
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1114, in __send_request
    async with self.session.stream(
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1602, in stream
    response = await self.send(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -5] No address associated with hostname```

**Comment by Zero6992** [comment]
Updated
