### ISSUE TITLE
Errors with Remote Desktop

### ISSUE THREAD

**Issue by Omupp** [Zero6992/chatGPT-discord-bot#56]
I ran the latest version and got the following error.
Probably due to the use of Xrdp

`playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1033/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-u1LdIB --remote-debugging-pipe --no-startup-window
<launched> pid=9917
[pid=9917][err] [9917:9917:1213/235312.524155:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
[pid=9917][err] [9917:9917:1213/235312.524839:ERROR:env.cc(255)] The platform failed to initialize.  Exiting. `

**Comment by Zero6992** [comment]
Is there a window manager for your remote desktop? Because running it will require opening a browser

**Comment by mohammalmokdad13** [comment]
Same thing, I was running the script from a bat file with nssm, and the browser does not open. Works fine when I run the bat file directly though, is there no way to run it without having to open the browser?

**Comment by Omupp** [comment]
The first error could be avoided by running `xvfb-run python3 main.py`
However, after 2 minutes of stoppage, the following error appeared

` Traceback (most recent call last):
  File "/opt/chatgpt2/main.py", line 1, in <module>
    from src import bot
  File "/opt/chatgpt2/src/bot.py", line 3, in <module>
    from src import responses
  File "/opt/chatgpt2/src/responses.py", line 32, in <module>
    chatbot = Chatbot(config, conversation_id=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 110, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  [Previous line repeated 24 more times]
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 311, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 381, in get_cf_cookies
    raise Exception("cf challenge fail")
Exception: cf challenge fail
root@kohta-desktop:/opt/chatgpt2# 
root@kohta-desktop:/opt/chatgpt2# xvfb-run python3.11 main.py
Traceback (most recent call last):
  File "/opt/chatgpt2/main.py", line 1, in <module>
    from src import bot
  File "/opt/chatgpt2/src/bot.py", line 3, in <module>
    from src import responses
  File "/opt/chatgpt2/src/responses.py", line 32, in <module>
    chatbot = Chatbot(config, conversation_id=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 110, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 312, in refresh_session
    self.refresh_session()
  [Previous line repeated 19 more times]
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 311, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/revChatGPT/revChatGPT.py", line 381, in get_cf_cookies
    raise Exception("cf challenge fail")
Exception: cf challenge fail
`

**Comment by Zero6992** [comment]
> The first error could be avoided by running `xvfb-run python3 main.py` However, after 2 minutes of stoppage, the following error appeared

Have you filled the session token?

**Comment by Omupp** [comment]
yes

**Comment by Zero6992** [comment]
same issue here [#324](https://github.com/acheong08/ChatGPT/issues/324)

**Comment by Zero6992** [comment]
Change to Using OpenAI official GPT-3 API now
