### ISSUE TITLE
Docker: Response.py is looking for config.json but only config.dev.json exists

### ISSUE THREAD

**Issue by ziipzaaapM16A4** [Zero6992/chatGPT-discord-bot#57]
In Docker
Response.py is looking for config.json but only config.dev.json exists

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src import bot
  File "/DiscordBot/src/bot.py", line 3, in <module>
    from src import responses
  File "/DiscordBot/src/responses.py", line 26, in <module>
    data = get_config()
  File "/DiscordBot/src/responses.py", line 20, in get_config
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/DiscordBot/config.json'
```

**Comment by Zero6992** [comment]
Change the file name of `config.dev.json` to `config.json`
