### ISSUE TITLE
Exception: Incorrect response from OpenAI API

### ISSUE THREAD

**Issue by Jiankun-Huang** [Zero6992/chatGPT-discord-bot#66]
Traceback (most recent call last):
  File "/home/jbx2050/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 215, in __get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jbx2050/chatGPT-discord-bot/src/bot.py", line 31, in send_message
    response += await responses.handle_response(user_message)
  File "/home/jbx2050/chatGPT-discord-bot/src/responses.py", line 7, in handle_response
    response = await chatbot.get_chat_response(prompt, output="text")
  File "/home/jbx2050/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 269, in get_chat_response
    return await self.__get_chat_text(data)
  File "/home/jbx2050/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 219, in __get_chat_text
    raise Exception("Incorrect response from OpenAI API") from exc
Exception: Incorrect response from OpenAI API

**Comment by Zero6992** [comment]
ChatGPT is down, OpenAI issue

```
ChatGPT is at capacity right now. We're experiencing exceptionally high demand. Please hang tight as we work on scaling our systems.
```

**Comment by Jiankun-Huang** [comment]
httpx.ReadTimeout: The read operation timed out
Is it also openai?

Full code `Traceback (most recent call last):
  File "/home/jbx2050/chatGPT-discord-bot/src/bot.py", line 31, in send_message
    response += await responses.handle_response(user_message)
  File "/home/jbx2050/chatGPT-discord-bot/src/responses.py", line 6, in handle_response
    chatbot.refresh_session()
  File "/home/jbx2050/.local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 314, in refresh_session
    response = s.get(
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 1045, in get
    return self.request(
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbx2050/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
`

**Comment by Zero6992** [comment]
refer #68
