### ISSUE TITLE
Exception: cf challenge fail

### ISSUE THREAD

**Issue by aW3ikun** [Zero6992/chatGPT-discord-bot#67]
Firstly, I ran `xvfb-run python3 -m revChatGPT --debug`, which works. 
But when I ran `main.py`, which raised `Exception: cf challenge fail`.  
How to resolve it?

``` zsh
root at linux in ~/chatGPT-discord-bot (main●) (venv) 
$ xvfb-run python3 -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Jg5jNxuyekaUYaRgmFz9dJrJSqt2BDsUGWW3PtAx0Gw-1671071986-0-1-8cc334c5.f08c3a00.d1bb330a-160
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

You:
Hi

Chatbot: 
Hello! How can I help you today? Is there something on your mind that you want
to talk about or ask about? I'm here to assist with any questions or concerns
you may have. Let me know if there's anything I can do to help.

You:
^C
Goodbye!


root at linux in ~/chatGPT-discord-bot (main●) (venv) 
$ xvfb-run python3 main.py              
Traceback (most recent call last):
  File "/root/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/root/chatGPT-discord-bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/root/chatGPT-discord-bot/src/responses.py", line 32, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/root/chatGPT-discord-bot/venv/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 116, in __init__
    self.refresh_session()
  File "/root/chatGPT-discord-bot/venv/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 295, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/chatGPT-discord-bot/venv/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 390, in get_cf_cookies
    raise Exception("cf challenge fail")
Exception: cf challenge fail
```

**Comment by aW3ikun** [comment]
I restarted docker several times. Success once.
It might be up to the openAI server status.

**Comment by Zero6992** [comment]
I's not running correctly now, right?

**Comment by aW3ikun** [comment]
> It's not running correctly now, right?

Just work not well.
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/23023918/207872022-44a7fa08-2fa4-4cdf-8354-04b726db3318.png">

**Comment by aW3ikun** [comment]
> It's not running correctly now, right?

It just works, but not well.
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/23023918/207872339-5ff27f11-1c74-436f-8dd1-9deea78b957e.png">

**Comment by aW3ikun** [comment]
Now.
```zsh
root at linux in ~/chatGPT-discord-bot (feature/support-docker-compose-up) 
$ docker compose up             
[+] Running 0/1
 ⠿ chatgpt-discord-bot Warning                                                       1.1s
[+] Building 225.7s (13/13) FINISHED                                                      
 => [internal] load build definition from Dockerfile                                 0.1s
 => => transferring dockerfile: 521B                                                 0.0s
 => [internal] load .dockerignore                                                    0.1s
 => => transferring context: 1.07kB                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                      0.0s
 => [1/8] FROM docker.io/library/ubuntu:20.04                                        0.0s
 => [internal] load build context                                                    0.0s
 => => transferring context: 34.07kB                                                 0.0s
 => CACHED [2/8] RUN apt-get update &&     apt-get install -yq tzdata &&     ln -fs  0.0s
 => [3/8] COPY ./ /DiscordBot                                                        0.2s
 => [4/8] WORKDIR /DiscordBot                                                        0.1s
 => [5/8] RUN pip install -r requirements.txt                                       25.6s
 => [6/8] RUN playwright install                                                    58.4s
 => [7/8] RUN playwright install-deps                                              101.2s 
 => [8/8] RUN apt-get install -y xvfb && apt-get install -y xauth                    8.0s 
 => exporting to image                                                              31.9s 
 => => exporting layers                                                             31.9s 
 => => writing image sha256:b2b6906dfcd36a17b5cbd84ba98f9110b86c4689c9ad86c684f3d75  0.0s 
 => => naming to docker.io/library/chatgpt-discord-bot                               0.0s 
                                                                                          
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/1
 ⠿ Container chatgpt-discord-bot  Created                                           62.0s
Attaching to chatgpt-discord-bot
chatgpt-discord-bot  | [2022-12-15 09:06:11] [INFO    ] discord.client: logging in using static token
chatgpt-discord-bot  | [2022-12-15 09:06:12] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 10591189c1a3815936267488cbdd5064).
chatgpt-discord-bot  | 2022-12-15 09:06:14 INFO     src.bot -> Send starting prompt with size 11
chatgpt-discord-bot  | 2022-12-15 09:06:32 INFO     src.bot -> Starting prompt response: Hello! It's nice to meet you. Is there anything I can help you with? I'm a large language model trained by OpenAI, so I can answer a wide range of questions on a variety of topics. Let me know if you have any questions and I'll do my best to help.
chatgpt-discord-bot  | 2022-12-15 09:06:33 INFO     src.bot -> ChatGPT_Bot#0000 is now running!
```

**Comment by Zero6992** [comment]
Can you receive other replies after the initial message?

**Comment by aW3ikun** [comment]
> Can you receive other replies after the initial message?

nope. 
we need official API.

**Comment by Zero6992** [comment]
Using OpenAI official GPT-3 API now

**Comment by aW3ikun** [comment]
> Using OpenAI official GPT-3 API now 

If possible， open a branch to store the bot of the revChatGPT version.
