### ISSUE TITLE
Issue when trying to use /chat for anything

### ISSUE THREAD

**Issue by Ishannaik** [Zero6992/chatGPT-discord-bot#68]
I am getting this issue whent trying to use /chat for anything in the latest version 0.2.5, also another issue which I am facing is after 3-4 hours the cookie expires and I have to manually add another new cookie, can anything be done about that to ensure 24/7 uptime of this bot.
```
2022-12-15 10:23:07 ERROR    src.bot -> Error while sending message: Incorrect response from OpenAI API
Traceback (most recent call last):
  File "C:\Users\ishan\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py", line 215, in __get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ishan\Downloads\chatGPT-discord-bot-0.2.5\src\bot.py", line 31, in send_message
    response += await responses.handle_response(user_message)
  File "C:\Users\ishan\Downloads\chatGPT-discord-bot-0.2.5\src\responses.py", line 7, in handle_response
    response = await chatbot.get_chat_response(prompt, output="text")
  File "C:\Users\ishan\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py", line 269, in get_chat_response
    return await self.__get_chat_text(data)
  File "C:\Users\ishan\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py", line 219, in __get_chat_text
    raise Exception("Incorrect response from OpenAI API") from exc
Exception: Incorrect response from OpenAI API
```

**Comment by Spudkip** [comment]
Did you ever figure this issue out?

**Comment by Zero6992** [comment]
Change to Using OpenAI official GPT-3 API now
